import type { ContentSection } from '../../types/content'

export const aehSections: ContentSection[] = [
  {
    id: 'direito-educacao-tratamento-saude',
    eyebrow: 'Fundamentos legais',
    title: 'O direito à educação continua durante o tratamento',
    blocks: [
      { type: 'paragraph', text: 'A hospitalização ou o tratamento de saúde podem afastar temporariamente a criança da instituição de Educação Infantil, mas não suspendem seu direito à educação.' },
      { type: 'paragraph', text: 'A Constituição Federal reconhece a educação como direito de todos e dever do Estado e da família. O Estatuto da Criança e do Adolescente também assegura, com prioridade, direitos como educação, saúde, dignidade, respeito, liberdade, cultura e lazer.' },
      { type: 'paragraph', text: 'A Lei de Diretrizes e Bases da Educação Nacional trata especificamente do atendimento durante o tratamento de saúde. O art. 4º-A assegura atendimento educacional, durante o período de internação, ao estudante da Educação Básica internado para tratamento de saúde em regime hospitalar ou domiciliar por tempo prolongado, conforme regulamentação do poder público em sua esfera de competência.' },
      { type: 'paragraph', text: 'Acrescentado à LDB pela Lei nº 14.952/2024, o art. 81-A determina que os sistemas de ensino estabeleçam, na Educação Básica e na Educação Superior, regime escolar especial para as situações previstas na lei. Entre elas estão os casos de estudantes impossibilitados de frequentar as aulas por tratamento de saúde ou por condição de saúde que impeça o acesso à instituição de ensino. A inclusão nesse regime depende da comprovação da situação e das condições estabelecidas em regulamento.' },
      {"type":"callout","tone":"guidance","title":"Para compreender as diferentes expressões","text":"Atendimento Educacional Hospitalar (AEH) designa aqui o trabalho educacional durante a hospitalização. A classe hospitalar é uma de suas formas de organização; o atendimento também pode ocorrer fora de uma sala exclusiva."},
      { type: 'paragraph', text: 'No Rio Grande do Norte, as normas estaduais utilizam a sigla AEHD para o Programa de Atendimento Educacional Hospitalar e Domiciliar.' },
      { type: 'paragraph', text: 'O Atendimento Educacional Especializado (AEE), por sua vez, é um atendimento complementar ou suplementar destinado ao público da Educação Especial. Por isso, não é sinônimo de AEH: a hospitalização, por si só, não torna a criança público do AEE. Quando uma criança já pertence ao público da Educação Especial e necessita desse atendimento, o AEE pode fazer parte dos apoios educacionais oferecidos, conforme as normas do sistema de ensino.' },
      {
        type: 'callout',
        tone: 'note',
        title: 'A organização no Rio Grande do Norte',
        text: 'No Rio Grande do Norte, a Portaria-SEI nº 533, de 6 de julho de 2022, da SEEC/RN, estabeleceu orientações para o Programa de Atendimento Educacional Hospitalar e Domiciliar da Rede Estadual, efetivado pelo NAEHD-RN em hospitais e casas de apoio que possuem Termo de Cooperação Técnica com a Secretaria Estadual de Educação. Essa informação se refere ao programa estadual regulado pela Portaria. No município de Natal, a Educação Infantil integra a responsabilidade do sistema municipal de ensino. A Portaria nº 087/2026-GS/SME, registrada no módulo de legislação, estabelece orientações para o atendimento no âmbito da SME/Natal. Essa organização pertence à esfera municipal e não se confunde com o programa estadual da SEEC/RN.',
      },
    ],
  },
  {
    id: 'educacao-infantil-contexto-hospitalar',
    eyebrow: 'Educação Infantil',
    title: 'Preservar a infância também no hospital',
    blocks: [
      {"type":"paragraph","text":"O foco são as crianças pequenas, de 4 anos a 5 anos e 11 meses, conforme a faixa etária da BNCC. As concepções e a organização curricular dessa etapa são aprofundadas no módulo Educação Infantil em Contexto Hospitalar."},
      {"type":"paragraph","text":"No hospital, o trabalho preserva as especificidades da Educação Infantil, sem antecipar práticas formais do Ensino Fundamental. Acompanhamento e registro ajudam a conhecer o percurso da criança, sem classificá-la."},
      { type: 'paragraph', text: 'As Diretrizes Curriculares Nacionais para a Educação Infantil definem as interações e a brincadeira como eixos das práticas pedagógicas. A BNCC apresenta os direitos de conviver, brincar, participar, explorar, expressar e conhecer-se e organiza o currículo da etapa em campos de experiências.' },
      { type: 'paragraph', text: 'No hospital, uma narrativa pode despertar conversa, desenho, faz de conta, movimento, criação de personagens ou apenas uma escuta atenta. Uma música pode convidar a criança a cantar, acompanhar o ritmo com o corpo, escolher sons ou simplesmente ouvir. O percurso não precisa ser igual para todas as crianças nem terminar em um produto definido previamente.' },
    ],
  },
  {
    id: 'crianca-cotidiano-hospitalar',
    eyebrow: 'Contexto e singularidades',
    title: 'O encontro pedagógico no cotidiano hospitalar',
    blocks: [
      {"type":"paragraph","text":"Exames, procedimentos, medicações, repouso e visitas de profissionais podem alterar o tempo e o espaço do encontro pedagógico."},
      {"type":"paragraph","text":"Por isso, duração, local e continuidade precisam ser ajustados a cada encontro."},
      {"type":"paragraph","text":"Perguntas e preferências da criança ajudam a orientar essa reorganização."},
      { type: 'paragraph', text: 'O atendimento pode acontecer no espaço da classe hospitalar, no leito ou em outro local previsto pela instituição. A escolha do espaço considera a organização do serviço e as orientações comunicadas pelos profissionais responsáveis.' },
      { type: 'paragraph', text: 'A brinquedoteca e a classe hospitalar têm funções e formas de organização que não devem ser confundidas automaticamente. Quando a brinquedoteca for utilizada em uma experiência pedagógica, a docente precisa considerar a organização da instituição e as orientações comunicadas pelos profissionais responsáveis.' },
      {
        type: 'list',
        items: [
          'o tempo disponível;',
          'o espaço em que a experiência acontece;',
          'os materiais que podem ser utilizados;',
          'a disposição da criança para conversar, brincar ou observar;',
          'as formas pelas quais ela consegue participar;',
          'a necessidade de fazer uma pausa ou encerrar o encontro;',
          'a possibilidade de retomar a experiência em outro momento.',
        ],
      },
    ],
  },
  {
    id: 'principios-pratica-pedagogica',
    eyebrow: 'Fundamentos da ação docente',
    title: 'Princípios que ajudam a orientar a prática',
    blocks: [
      {"type":"callout","tone":"guidance","title":"Acolher sem abandonar a intenção pedagógica","text":"A docente pode chegar com uma proposta e encontrar uma criança que deseja conversar, prefere observar ou precisa interromper a história. Acolher essas manifestações ajuda a decidir o que é possível naquele encontro."},
      {"type":"callout","tone":"highlight","title":"Acolhimento e intencionalidade caminham juntos","text":"As referências curriculares estão desenvolvidas no módulo Educação Infantil; a preparação e a retomada das propostas, no módulo Planejamento Pedagógico."},
    ],
  },
  {
    id: 'papel-limites-atuacao-docente',
    eyebrow: 'Docência',
    title: 'O papel da docente no Atendimento Educacional Hospitalar',
    blocks: [
      {"type":"paragraph","text":"A docente planeja, acompanha e documenta experiências educativas, articulando conhecimento pedagógico, escuta e observação."},
      { type: 'paragraph', text: 'As normas estaduais atribuem ao docente do AEHD responsabilidades como planejar e acompanhar o trabalho pedagógico, manter os registros previstos pelo sistema, produzir relatórios, dialogar com a instituição de matrícula e articular seu trabalho com o NAEHD-RN e com a instituição onde o atendimento acontece.' },
      {"type":"paragraph","text":"Na Educação Infantil, os registros acompanham interesses, interações e brincadeiras, sem classificar a criança."},
      {"type":"paragraph","text":"A família pode compartilhar interesses e formas de comunicação da criança. A instituição de matrícula contribui com seu percurso educativo e a manutenção dos vínculos."},
      {"type":"paragraph","text":"Os profissionais de saúde comunicam as orientações necessárias sobre tempo, posicionamento, materiais e outras condições do atendimento. Essas trocas devem se limitar ao que é pertinente ao trabalho educacional e preservar a privacidade."},
      {"type":"paragraph","text":"A articulação e os registros seguem as normas da rede responsável pelo atendimento."},
      {
        type: 'callout',
        tone: 'note',
        title: 'A atuação docente possui uma especificidade própria',
        text: 'A docente acompanha a experiência educativa. Não cabe a ela diagnosticar, avaliar clinicamente, prescrever cuidados ou substituir profissionais de saúde. As orientações clínicas necessárias devem partir dos profissionais responsáveis.',
      },
    ],
  },
  {
    id: 'planejamento-flexivel-contextualizado',
    eyebrow: 'Planejamento',
    title: 'Preparar possibilidades e acompanhar o encontro',
    blocks: [
      {"type":"paragraph","text":"Prepare uma intenção e possibilidades de participação, considerando materiais, espaço e orientações institucionais. O módulo Planejamento Pedagógico aprofunda esse processo."},
      { type: 'paragraph', text: 'Uma experiência com literatura, por exemplo, pode envolver escuta, conversa, escolha de personagens, reconto, desenho, movimento, criação de outro final ou brincadeira de faz de conta. Essas possibilidades não formam uma sequência obrigatória. A docente pode acolher os caminhos que surgem e decidir, junto com a criança, o que faz sentido naquele momento.' },
      {"type":"callout","tone":"guidance","title":"Registro e retomada","text":"Uma conversa, uma escolha ou um gesto podem merecer registro, mesmo sem produção material. Anotar o que mobilizou a criança ajuda a retomar uma narrativa interrompida, lembrar preferências e reorganizar os materiais."},
    ],
  },
  {
    id: 'escuta-escolhas-participacao',
    eyebrow: 'Participação da criança',
    title: 'Escutar, oferecer escolhas e respeitar a recusa',
    blocks: [
      {"type":"paragraph","text":"Na internação, a criança pode ter menos oportunidades de decidir sobre seu cotidiano. Escolher uma história, um personagem ou uma brincadeira abre um espaço de autonomia no encontro pedagógico."},
      {"type":"paragraph","text":"Apresente os materiais como um convite e dê tempo para que a criança os conheça. Pergunte como gostaria de participar e acolha suas sugestões."},
      {"type":"paragraph","text":"Observar, escutar e aproximar-se aos poucos também são formas de participar. Uma pausa ou a decisão de não continuar devem ser respeitadas."},
      {"type":"paragraph","text":"Gestos, olhares e silêncios ajudam a compreender o encontro, mas não autorizam concluir, por si sós, uma causa clínica ou emocional."},
      {"type":"callout","tone":"guidance","title":"Quando a criança não deseja participar","text":"Acolha a recusa sem tratá-la como falta de interesse pela aprendizagem. Se houver abertura, converse e ofereça outra possibilidade. Em alguns encontros, respeitar a decisão de não participar será a escolha mais coerente."},
    ],
  },
  {
    id: 'sintese-para-pratica',
    eyebrow: 'Síntese e referências',
    title: 'Para levar deste módulo',
    blocks: [
      {"type":"paragraph","text":"Para refletir sobre a organização do atendimento:"},
      {
        type: 'list',
        items: [
          'Como tenho reconhecido as diferentes formas de participação da criança?',
          'Que espaço suas escolhas encontram no planejamento?',
          'As brincadeiras e as interações estão no centro da experiência?',
          'O que precisa mudar quando o encontro não acontece como foi imaginado?',
          'Meus registros documentam o percurso vivido ou apenas o resultado de uma atividade?',
          'Estou preservando os limites entre a observação pedagógica e as decisões clínicas?',
          'O que cada encontro ensina sobre a criança e sobre minha própria prática?',
        ],
      },
      { type: 'paragraph', text: 'Referências acadêmicas utilizadas:' },
      {
        type: 'list',
        items: [
          'HOLANDA, Eliane Rolim de; COLLET, Neusa. As dificuldades da escolarização da criança com doença crônica no contexto hospitalar. Revista da Escola de Enfermagem da USP, São Paulo, v. 45, n. 2, p. 381-389, 2011.',
          'OLIVEIRA, Senadaht Barbosa Baracho Rodrigues de. Acompanhamento educacional no hospital e na escola regular: o que dizem crianças, mães e professoras. 2022. 285 f. Tese (Doutorado em Educação) — Programa de Pós-Graduação em Educação, Centro de Educação, Universidade Federal do Rio Grande do Norte, Natal, 2022.',
          'ROLIM, Carmem Lúcia Artioli; GÓES, Maria Cecília Rafael de. Crianças com câncer e o atendimento educacional nos ambientes hospitalar e escolar. Educação e Pesquisa, São Paulo, v. 35, n. 3, p. 509-523, set./dez. 2009.',
        ],
      },
      { type: 'paragraph', text: 'Documentos oficiais consultados:' },
      {
        type: 'resources',
        items: [
          {
            id: 'constituicao-federal',
            type: 'document',
            title: 'Constituição da República Federativa do Brasil de 1988',
            description: 'Fundamentos do direito à educação e da proteção integral à criança.',
            meta: 'Presidência da República · arts. 205, 208 e 227',
            href: 'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm',
          },
          {
            id: 'eca',
            type: 'document',
            title: 'Estatuto da Criança e do Adolescente',
            description: 'Lei nº 8.069/1990, em texto compilado.',
            meta: 'Presidência da República',
            href: 'https://www.planalto.gov.br/ccivil_03/leis/l8069.htm',
          },
          {
            id: 'ldb',
            type: 'document',
            title: 'Lei de Diretrizes e Bases da Educação Nacional',
            description: 'Lei nº 9.394/1996, incluindo os arts. 4º-A e 81-A.',
            meta: 'Presidência da República · texto compilado',
            href: 'https://www.planalto.gov.br/ccivil_03/leis/l9394.htm',
          },
          {
            id: 'resolucao-cne-ceb-2-2001',
            type: 'document',
            title: 'Resolução CNE/CEB nº 2/2001',
            description: 'Diretrizes Nacionais para a Educação Especial na Educação Básica.',
            meta: 'Ministério da Educação',
            href: 'https://www.gov.br/mec/pt-br/cne/normas-classificadas-por-assunto/normativos-sobre-educacao-especial',
          },
          {
            id: 'orientacoes-classe-hospitalar',
            type: 'document',
            title: 'Classe hospitalar e atendimento pedagógico domiciliar',
            description: 'Estratégias e orientações para a organização do atendimento.',
            meta: 'MEC/SEESP · 2002',
            href: 'https://dominiopublico.mec.gov.br/pesquisa/DetalheObraForm.do?co_obra=17039&select_action=',
          },
          {
            id: 'dcnei',
            type: 'document',
            title: 'Diretrizes Curriculares Nacionais para a Educação Infantil',
            description: 'Publicação que reúne a Resolução CNE/CEB nº 5/2009.',
            meta: 'Ministério da Educação',
            href: 'https://www.gov.br/mec/pt-br/acesso-a-informacao/media/seb/pdf/d_c_n_educacao_basica_nova.pdf',
          },
          {
            id: 'bncc',
            type: 'document',
            title: 'Base Nacional Comum Curricular',
            description: 'Referência curricular nacional para a Educação Infantil.',
            meta: 'Ministério da Educação',
            href: 'https://basenacionalcomum.mec.gov.br/',
          },
          {
            id: 'portaria-rn-533-2022',
            type: 'document',
            title: 'Portaria-SEI nº 533, de 6 de julho de 2022',
            description: 'Ato da SEEC/RN com orientações para implementação e funcionamento do Programa de Atendimento Educacional Hospitalar e Domiciliar do RN.',
            meta: 'Diário Oficial do Estado do Rio Grande do Norte',
            href: 'https://webdisk.diariooficial.rn.gov.br/Jornal/12022-07-22.pdf',
          },
          {
            id: 'portaria-rn-4522-2024',
            type: 'document',
            title: 'Portaria-SEI nº 4.522, de 26 de setembro de 2024',
            description: 'Ato da SEEC/RN sobre Educação Especial Inclusiva que contém seção específica sobre AEHD e atribuições de seus professores.',
            meta: 'Diário Oficial do Estado do Rio Grande do Norte',
            href: 'https://webdisk.diariooficial.rn.gov.br/Jornal/12024-09-27.pdf',
          },
        ],
      },
    ],
  },
]
