import type { ContentSection } from '../../types/content'

export const aehSections: ContentSection[] = [
  {
    id: 'direito-educacao-tratamento-saude',
    eyebrow: 'Fundamentos legais',
    title: 'O direito à educação continua durante o tratamento',
    blocks: [
      { type: 'paragraph', text: 'A hospitalização ou o tratamento de saúde podem afastar temporariamente a criança da instituição de Educação Infantil, mas não suspendem seu direito à educação.' },
      { type: 'paragraph', text: 'A Constituição Federal reconhece a educação como direito de todos e dever do Estado e da família. O Estatuto da Criança e do Adolescente também assegura, com prioridade, direitos como educação, saúde, dignidade, respeito, liberdade, cultura e lazer.' },
      { type: 'paragraph', text: 'A Lei de Diretrizes e Bases da Educação Nacional trata especificamente do atendimento durante o tratamento de saúde. O art. 4º-A assegura atendimento educacional, durante o período de internação, ao estudante da Educação Básica internado para tratamento de saúde em regime hospitalar ou domiciliar por tempo prolongado, conforme regulamentação do poder público em sua esfera de competência.' },
      { type: 'paragraph', text: 'Acrescentado à LDB pela Lei nº 14.952/2024, o art. 81-A determina que os sistemas de ensino estabeleçam, na Educação Básica e na Educação Superior, regime escolar especial para as situações previstas na lei. Entre elas estão os casos de estudantes impossibilitados de frequentar as aulas por tratamento de saúde ou por condição de saúde que impeça o acesso à instituição de ensino. A inclusão nesse regime depende da comprovação da situação e das condições estabelecidas em regulamento.' },
      { type: 'paragraph', text: 'Essas garantias legais são importantes porque afirmam que o tratamento de saúde não pode tornar a criança invisível para a educação. A forma como o atendimento será oferecido, porém, depende das normas e da organização de cada sistema de ensino.' },
      {
        type: 'callout',
        tone: 'guidance',
        title: 'Para compreender as diferentes expressões',
        text: 'Neste Caderno, Atendimento Educacional Hospitalar (AEH) é a expressão utilizada para o trabalho educacional desenvolvido durante a hospitalização. A classe hospitalar é uma das formas de organizar esse atendimento no hospital. Isso significa que nem toda experiência educativa realizada no ambiente hospitalar acontece necessariamente em uma sala exclusiva ou em uma estrutura denominada classe hospitalar.',
      },
      { type: 'paragraph', text: 'No Rio Grande do Norte, as normas estaduais utilizam a sigla AEHD para o Programa de Atendimento Educacional Hospitalar e Domiciliar.' },
      { type: 'paragraph', text: 'O Atendimento Educacional Especializado (AEE), por sua vez, é um atendimento complementar ou suplementar destinado ao público da Educação Especial. Por isso, não é sinônimo de AEH: a hospitalização, por si só, não torna a criança público do AEE. Quando uma criança já pertence ao público da Educação Especial e necessita desse atendimento, o AEE pode fazer parte dos apoios educacionais oferecidos, conforme as normas do sistema de ensino.' },
      {
        type: 'callout',
        tone: 'note',
        title: 'A organização no Rio Grande do Norte',
        text: 'No Rio Grande do Norte, a Portaria-SEI nº 533, de 6 de julho de 2022, da SEEC/RN, estabeleceu orientações para o Programa de Atendimento Educacional Hospitalar e Domiciliar da Rede Estadual, efetivado pelo NAEHD-RN em hospitais e casas de apoio que possuem Termo de Cooperação Técnica com a Secretaria Estadual de Educação. Essa informação se refere ao programa estadual regulado pela Portaria. No município de Natal, a Educação Infantil integra a responsabilidade do sistema municipal de ensino. A Portaria nº 087/2026-GS/SME, registrada no módulo de legislação, estabelece orientações para o atendimento no âmbito da SME/Natal. Essa organização pertence à esfera municipal e não se confunde com o programa estadual da SEEC/RN.',
      },
      {
        type: 'callout',
        tone: 'highlight',
        title: 'O direito permanece, mas a forma de oferta pode variar',
        text: 'O direito à educação acompanha a criança durante o tratamento. A organização do atendimento, os critérios de acesso, os profissionais envolvidos e os registros solicitados dependem das normas do sistema de ensino e dos acordos institucionais existentes em cada contexto.',
      },
    ],
  },
  {
    id: 'educacao-infantil-contexto-hospitalar',
    eyebrow: 'Educação Infantil',
    title: 'Preservar a infância também no hospital',
    blocks: [
      { type: 'paragraph', text: 'Este Caderno Digital se dirige principalmente ao trabalho com “crianças pequenas”, expressão utilizada pela Base Nacional Comum Curricular para a faixa de 4 anos a 5 anos e 11 meses. No município de Natal, a oferta da Educação Infantil integra a responsabilidade do sistema municipal de ensino.' },
      { type: 'paragraph', text: 'Mesmo durante a hospitalização, as propostas destinadas a essas crianças precisam preservar as concepções e as especificidades da Educação Infantil. Isso significa reconhecer que a criança aprende e produz conhecimentos enquanto brinca, interage, explora, imagina, pergunta, observa, cria e se expressa por diferentes linguagens.' },
      { type: 'paragraph', text: 'As Diretrizes Curriculares Nacionais para a Educação Infantil definem as interações e a brincadeira como eixos das práticas pedagógicas. A BNCC apresenta os direitos de conviver, brincar, participar, explorar, expressar e conhecer-se e organiza o currículo da etapa em campos de experiências.' },
      { type: 'paragraph', text: 'Esses elementos não precisam ser usados como partes isoladas de um planejamento ou como itens que a docente deve marcar mecanicamente. Eles ajudam a pensar a experiência de maneira integrada, observando o que a criança vive, como participa, que relações constrói e quais possibilidades podem ser ampliadas.' },
      { type: 'paragraph', text: 'No hospital, uma narrativa pode despertar conversa, desenho, faz de conta, movimento, criação de personagens ou apenas uma escuta atenta. Uma música pode convidar a criança a cantar, acompanhar o ritmo com o corpo, escolher sons ou simplesmente ouvir. O percurso não precisa ser igual para todas as crianças nem terminar em um produto definido previamente.' },
      {
        type: 'list',
        items: [
          'As interações e as brincadeiras continuam sendo centrais.',
          'Os conhecimentos, as histórias e as preferências da criança fazem parte da experiência.',
          'As diferentes linguagens podem aparecer de maneira articulada.',
          'Educar e cuidar permanecem inseparáveis.',
          'A participação pode acontecer de diferentes formas e intensidades.',
          'As propostas não devem antecipar práticas formais próprias do Ensino Fundamental.',
          'A observação e o registro acompanham o percurso vivido, sem classificar ou rotular a criança.',
        ],
      },
      {
        type: 'callout',
        tone: 'guidance',
        title: 'Uma experiência não se reduz ao cumprimento de uma tarefa',
        text: 'A intencionalidade pedagógica aparece nas escolhas da docente, na maneira como ela organiza possibilidades, escuta a criança e acompanha o encontro. O sentido da experiência não é definido apenas pelo planejamento: ele também se constrói na relação com a criança.',
      },
    ],
  },
  {
    id: 'crianca-cotidiano-hospitalar',
    eyebrow: 'Contexto e singularidades',
    title: 'O encontro pedagógico no cotidiano hospitalar',
    blocks: [
      { type: 'paragraph', text: 'O cotidiano hospitalar tem seus próprios tempos, espaços e acontecimentos. Exames, procedimentos, medicações, repouso e visitas de profissionais de saúde podem modificar o encontro que havia sido imaginado pela docente.' },
      { type: 'paragraph', text: 'Uma proposta pode precisar começar mais tarde, durar menos tempo, mudar de espaço, ser interrompida ou ficar para outro momento. Também pode seguir um caminho que não estava previsto inicialmente.' },
      { type: 'paragraph', text: 'Essas mudanças não significam que o planejamento falhou. Elas fazem parte de um contexto no qual a docente precisa observar, escutar e reorganizar suas escolhas sem perder a intenção pedagógica.' },
      { type: 'paragraph', text: 'A hospitalização faz parte do momento vivido pela criança, mas não define quem ela é. Ela continua sendo sujeito de direitos, que brinca, imagina, participa, aprende, cria relações e produz sentidos sobre o mundo. Continua trazendo histórias, conhecimentos, perguntas, preferências e maneiras próprias de viver a infância.' },
      { type: 'paragraph', text: 'O atendimento pode acontecer no espaço da classe hospitalar, no leito ou em outro local previsto pela instituição. A escolha do espaço considera a organização do serviço e as orientações comunicadas pelos profissionais responsáveis.' },
      { type: 'paragraph', text: 'A brinquedoteca e a classe hospitalar têm funções e formas de organização que não devem ser confundidas automaticamente. Quando a brinquedoteca for utilizada em uma experiência pedagógica, a docente precisa considerar a organização da instituição e as orientações comunicadas pelos profissionais responsáveis.' },
      {
        type: 'list',
        items: [
          'o tempo disponível;',
          'o espaço em que a experiência acontece;',
          'os materiais que podem ser utilizados;',
          'a disposição da criança para conversar, brincar ou observar;',
          'as formas pelas quais ela consegue participar;',
          'a necessidade de fazer uma pausa ou encerrar o encontro;',
          'a possibilidade de retomar a experiência em outro momento.',
        ],
      },
      { type: 'paragraph', text: 'Esses pontos não formam um protocolo. Eles ajudam a lembrar que cada encontro possui condições próprias e precisa ser construído com atenção ao que acontece naquele momento.' },
      {
        type: 'callout',
        tone: 'note',
        title: 'Observar é uma ação pedagógica',
        text: 'A docente observa como a criança se aproxima, se comunica e participa para pensar suas decisões pedagógicas. Avaliar condições clínicas, prescrever cuidados ou autorizar procedimentos não faz parte de sua atuação. As informações de saúde necessárias ao atendimento devem ser comunicadas pelos profissionais responsáveis, dentro dos limites da privacidade e da função de cada área.',
      },
    ],
  },
  {
    id: 'principios-pratica-pedagogica',
    eyebrow: 'Fundamentos da ação docente',
    title: 'Princípios que ajudam a orientar a prática',
    blocks: [
      { type: 'paragraph', text: 'A prática docente no Atendimento Educacional Hospitalar se constrói no encontro entre os direitos da criança, as especificidades da Educação Infantil, os conhecimentos profissionais da docente e as condições do contexto hospitalar.' },
      {
        type: 'list',
        items: [
          'A criança é sujeito histórico, social e de direitos.',
          'Interações e brincadeiras são eixos da Educação Infantil.',
          'Educar e cuidar fazem parte da mesma experiência.',
          'Escutar a criança também é uma ação pedagógica.',
          'A participação pode acontecer pela fala, pelo corpo, pelo brincar, pela escolha, pela criação, pelo silêncio ou pela observação.',
          'Planejar exige intencionalidade e abertura para mudanças.',
          'As diferentes linguagens ampliam as possibilidades de expressão e participação.',
          'Cada encontro é singular e não precisa produzir o mesmo resultado.',
          'A articulação com a família, a instituição de matrícula e os profissionais do hospital deve respeitar os limites e as responsabilidades de cada área.',
          'A prática docente envolve autoria, reflexão e decisões construídas a partir do que a docente observa e conhece.',
        ],
      },
      { type: 'paragraph', text: 'Esses princípios orientam decisões que tomam forma em cada encontro. Ao retomá-los, a docente relaciona suas escolhas ao que observa e às mudanças que a experiência pede.' },
      {
        type: 'callout',
        tone: 'guidance',
        title: 'Acolher sem abandonar a intenção pedagógica',
        text: 'Acolhimento e planejamento fazem parte da responsabilidade docente. A docente prepara possibilidades e as reorganiza quando a experiência segue outro caminho. Pode chegar com uma proposta e perceber que a criança deseja apenas conversar, oferecer uma brincadeira e acolher sua escolha de observar ou interromper uma história quando o encontro assim exigir. A decisão pedagógica se constrói entre o que havia sido planejado e o que se torna possível com aquela criança.',
      },
      {
        type: 'callout',
        tone: 'highlight',
        title: 'Acolhimento e intencionalidade caminham juntos',
        text: 'Na escuta e no respeito ao tempo da criança, a docente sustenta sua intenção pedagógica enquanto reconhece a hora de adaptar, pausar ou retomar uma experiência.',
      },
    ],
  },
  {
    id: 'papel-limites-atuacao-docente',
    eyebrow: 'Docência',
    title: 'O papel da docente no Atendimento Educacional Hospitalar',
    blocks: [
      { type: 'paragraph', text: 'A docente organiza e acompanha experiências coerentes com a Educação Infantil e com as possibilidades de participação da criança. Para isso, mobiliza conhecimentos pedagógicos, observa, escuta, registra e reflete sobre o que acontece em cada encontro.' },
      { type: 'paragraph', text: 'Seu trabalho vai além da aplicação de atividades. A docente conhece a criança e acompanha o encontro para decidir que caminhos pedagógicos fazem sentido.' },
      { type: 'paragraph', text: 'As normas estaduais atribuem ao docente do AEHD responsabilidades como planejar e acompanhar o trabalho pedagógico, manter os registros previstos pelo sistema, produzir relatórios, dialogar com a instituição de matrícula e articular seu trabalho com o NAEHD-RN e com a instituição onde o atendimento acontece.' },
      { type: 'paragraph', text: 'Na Educação Infantil, essas atribuições precisam ser relacionadas às especificidades da etapa e às formas próprias de acompanhamento das experiências das crianças. O registro não deve classificar a criança, medir seu desempenho ou antecipar práticas de aprovação e retenção. Ele pode documentar interesses, interações, brincadeiras, escolhas, formas de expressão e caminhos construídos durante o atendimento.' },
      {
        type: 'callout',
        tone: 'guidance',
        title: 'Relações necessárias ao trabalho',
        text: 'O diálogo com a família, com a instituição de matrícula e com os profissionais do hospital pode contribuir para a organização do atendimento. A família pode compartilhar informações sobre os interesses, as experiências e as formas de comunicação da criança. A instituição de matrícula pode ajudar a manter vínculos e oferecer informações sobre o percurso educativo. Os profissionais responsáveis pelo cuidado podem comunicar orientações necessárias sobre tempo, posicionamento, materiais ou outras condições relacionadas ao encontro.',
      },
      { type: 'paragraph', text: 'Essas trocas precisam se limitar ao que é pertinente ao trabalho educacional e preservar a privacidade da criança.' },
      {
        type: 'list',
        items: [
          'acolher a criança e apresentar a proposta como um convite;',
          'conhecer seus interesses e suas formas de comunicação;',
          'planejar experiências coerentes com a Educação Infantil;',
          'selecionar materiais possíveis para aquele contexto;',
          'observar, acompanhar e documentar o percurso vivido;',
          'dialogar com a família e com a instituição de matrícula quando necessário;',
          'articular o trabalho com o NAEHD-RN e com a instituição onde acontece o atendimento;',
          'participar de estudos e processos de formação continuada;',
          'refletir sobre as próprias escolhas e ampliar seu repertório.',
        ],
      },
      { type: 'paragraph', text: 'A forma como essas possibilidades se concretizam depende das normas do sistema de ensino, da organização institucional e das condições de cada atendimento.' },
      {
        type: 'callout',
        tone: 'note',
        title: 'A atuação docente possui uma especificidade própria',
        text: 'A docente acompanha a experiência educativa. Não cabe a ela diagnosticar, avaliar clinicamente, prescrever cuidados ou substituir profissionais de saúde. As orientações clínicas necessárias devem partir dos profissionais responsáveis.',
      },
    ],
  },
  {
    id: 'planejamento-flexivel-contextualizado',
    eyebrow: 'Planejamento',
    title: 'Preparar possibilidades e acompanhar o encontro',
    blocks: [
      { type: 'paragraph', text: 'Planejar no Atendimento Educacional Hospitalar é preparar possibilidades sem determinar rigidamente tudo o que deverá acontecer.' },
      { type: 'paragraph', text: 'A docente pensa em uma intenção para o encontro, considera as especificidades da Educação Infantil, seleciona materiais e imagina diferentes formas de participação. Ao mesmo tempo, permanece atenta ao que a criança comunica e às mudanças do cotidiano hospitalar.' },
      { type: 'paragraph', text: 'Uma experiência com literatura, por exemplo, pode envolver escuta, conversa, escolha de personagens, reconto, desenho, movimento, criação de outro final ou brincadeira de faz de conta. Essas possibilidades não formam uma sequência obrigatória. A docente pode acolher os caminhos que surgem e decidir, junto com a criança, o que faz sentido naquele momento.' },
      { type: 'paragraph', text: 'Os direitos de aprendizagem e desenvolvimento e os campos de experiências ajudam a interpretar e ampliar o que a criança vive. Eles não precisam ser selecionados como partes isoladas nem usados para enquadrar antecipadamente todas as ações da criança.' },
      { type: 'paragraph', text: 'Planejar com flexibilidade também não significa agir sem intenção. Significa conhecer diferentes possibilidades, perceber o que o encontro permite e reorganizar o percurso quando necessário.' },
      {
        type: 'list',
        items: [
          'Que possibilidades de brincar, interagir, explorar e se expressar esta experiência pode abrir?',
          'Como a criança poderá participar de diferentes maneiras?',
          'O que seus gestos, escolhas, palavras ou silêncios estão comunicando?',
          'Os materiais e o espaço são possíveis para este encontro?',
          'Há alguma orientação institucional que precisa ser considerada?',
          'A proposta pode ser adaptada, interrompida ou retomada?',
          'Que escolhas reais podem ser oferecidas à criança?',
          'O que merece ser observado e registrado?',
          'O que a experiência revela sobre a criança e sobre as decisões da docente?',
        ],
      },
      { type: 'paragraph', text: 'Essas perguntas não precisam ser respondidas como um formulário. Elas podem acompanhar a preparação, a observação e a reflexão posterior ao encontro.' },
      {
        type: 'callout',
        tone: 'guidance',
        title: 'Registro e retomada',
        text: 'O registro ajuda a docente a lembrar o que aconteceu, reconhecer interesses, acompanhar percursos e pensar em outras possibilidades. Nem toda experiência precisa gerar uma produção material. Uma conversa, uma escolha, uma brincadeira breve, um gesto de aproximação ou a decisão de observar também podem ser significativos e merecer atenção. O registro pode ajudar a retomar uma narrativa interrompida, lembrar uma preferência, reorganizar materiais ou perceber como a criança vem construindo sua participação ao longo dos encontros.',
      },
      {
        type: 'callout',
        tone: 'highlight',
        title: 'Flexibilidade faz parte do planejamento',
        text: 'O planejamento flexível reúne intenção pedagógica, conhecimento profissional, escuta da criança e atenção ao contexto. Ele não define previamente todos os resultados: prepara caminhos que podem ser ajustados durante a experiência.',
      },
    ],
  },
  {
    id: 'escuta-escolhas-participacao',
    eyebrow: 'Participação da criança',
    title: 'Escutar, oferecer escolhas e respeitar a recusa',
    blocks: [
      { type: 'paragraph', text: 'Durante a hospitalização, muitos tempos, deslocamentos e decisões cotidianas da criança podem ficar mais restritos. Nas experiências pedagógicas, encontrar possibilidades reais de escolha pode fortalecer sua participação e sua autonomia.' },
      { type: 'paragraph', text: 'A docente pode apresentar a proposta como um convite, explicar o que imaginou, mostrar os materiais e perguntar como a criança gostaria de participar. Escolher uma história, uma cor, um objeto, um personagem, uma brincadeira ou o ponto de partida pode ser significativo.' },
      { type: 'paragraph', text: 'Participar, porém, não significa necessariamente falar, produzir alguma coisa ou realizar toda a proposta. A criança pode observar, escutar, sugerir uma mudança, fazer uma pausa, aproximar-se aos poucos ou decidir não continuar.' },
      { type: 'paragraph', text: 'A escuta não acontece apenas pela fala. O corpo, o olhar, o silêncio, a aproximação, o afastamento e as mudanças propostas pela criança também comunicam. Essas manifestações precisam ser observadas com cuidado, sem atribuir automaticamente uma causa clínica ou emocional.' },
      {
        type: 'list',
        items: [
          'apresentar os materiais e permitir tempo para que a criança os conheça;',
          'conversar sobre seus interesses, brincadeiras e narrativas;',
          'oferecer escolhas compreensíveis e possíveis naquele momento;',
          'acolher ideias e mudanças propostas pela criança;',
          'reconhecer a observação e a escuta como formas de participação;',
          'permitir pausas e mudanças de percurso;',
          'manter aberta a possibilidade de retomar a experiência;',
          'respeitar quando a criança não deseja participar.',
        ],
      },
      { type: 'paragraph', text: 'Essas possibilidades não são etapas que precisam ser cumpridas. Elas podem ajudar a docente a construir uma relação na qual a criança tenha espaço para se expressar e influenciar o encontro.' },
      {
        type: 'callout',
        tone: 'guidance',
        title: 'Quando a criança não deseja participar',
        text: 'A recusa é uma forma possível de comunicação e precisa ser respeitada. Ela não deve ser interpretada imediatamente como falta de interesse pela aprendizagem. Também não cabe à docente concluir que a recusa foi causada por cansaço, medo, desconforto ou qualquer condição clínica ou emocional específica. Quando for possível, a docente pode acolher a manifestação, conversar com a criança e deixar aberta outra possibilidade. Em alguns encontros, respeitar a decisão de não participar será a escolha mais coerente.',
      },
      {
        type: 'callout',
        tone: 'highlight',
        title: 'Participar também é poder escolher',
        text: 'A participação se fortalece quando a criança percebe que suas escolhas, seus tempos e suas formas de expressão são considerados. A docente continua responsável por organizar a experiência, mas não precisa controlar todos os caminhos que ela poderá seguir.',
      },
    ],
  },
  {
    id: 'sintese-para-pratica',
    eyebrow: 'Síntese e referências',
    title: 'Para levar deste módulo',
    blocks: [
      {
        type: 'callout',
        tone: 'highlight',
        title: 'Síntese do módulo',
        text: 'A hospitalização faz parte do momento vivido pela criança, mas não define quem ela é. Ela continua sendo sujeito de direitos, que brinca, imagina, participa, aprende, cria relações e produz sentidos sobre o mundo.',
      },
      { type: 'paragraph', text: 'No Atendimento Educacional Hospitalar, garantir o direito à educação também significa preservar as especificidades da Educação Infantil. Interações, brincadeiras, diferentes linguagens, escuta, participação, educar e cuidar continuam presentes, ainda que assumam formas próprias em cada encontro.' },
      { type: 'paragraph', text: 'A docente prepara possibilidades, acompanha o que a criança comunica e reorganiza o percurso quando necessário. Seu trabalho tem uma especificidade pedagógica e não se confunde com avaliação clínica, diagnóstico ou orientação de saúde.' },
      { type: 'paragraph', text: 'Perguntas para retomar:' },
      {
        type: 'list',
        items: [
          'Como tenho reconhecido as diferentes formas de participação da criança?',
          'Que espaço suas escolhas encontram no planejamento?',
          'As brincadeiras e as interações estão no centro da experiência?',
          'O que precisa mudar quando o encontro não acontece como foi imaginado?',
          'Meus registros documentam o percurso vivido ou apenas o resultado de uma atividade?',
          'Estou preservando os limites entre a observação pedagógica e as decisões clínicas?',
          'O que cada encontro ensina sobre a criança e sobre minha própria prática?',
        ],
      },
      { type: 'paragraph', text: 'Referências acadêmicas utilizadas:' },
      {
        type: 'list',
        items: [
          'HOLANDA, Eliane Rolim de; COLLET, Neusa. As dificuldades da escolarização da criança com doença crônica no contexto hospitalar. Revista da Escola de Enfermagem da USP, São Paulo, v. 45, n. 2, p. 381-389, 2011.',
          'OLIVEIRA, Senadaht Barbosa Baracho Rodrigues de. Acompanhamento educacional no hospital e na escola regular: o que dizem crianças, mães e professoras. 2022. 285 f. Tese (Doutorado em Educação) — Programa de Pós-Graduação em Educação, Centro de Educação, Universidade Federal do Rio Grande do Norte, Natal, 2022.',
          'ROLIM, Carmem Lúcia Artioli; GÓES, Maria Cecília Rafael de. Crianças com câncer e o atendimento educacional nos ambientes hospitalar e escolar. Educação e Pesquisa, São Paulo, v. 35, n. 3, p. 509-523, set./dez. 2009.',
        ],
      },
      { type: 'paragraph', text: 'Documentos oficiais consultados:' },
      {
        type: 'resources',
        items: [
          {
            id: 'constituicao-federal',
            type: 'document',
            title: 'Constituição da República Federativa do Brasil de 1988',
            description: 'Fundamentos do direito à educação e da proteção integral à criança.',
            meta: 'Presidência da República · arts. 205, 208 e 227',
            href: 'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm',
          },
          {
            id: 'eca',
            type: 'document',
            title: 'Estatuto da Criança e do Adolescente',
            description: 'Lei nº 8.069/1990, em texto compilado.',
            meta: 'Presidência da República',
            href: 'https://www.planalto.gov.br/ccivil_03/leis/l8069.htm',
          },
          {
            id: 'ldb',
            type: 'document',
            title: 'Lei de Diretrizes e Bases da Educação Nacional',
            description: 'Lei nº 9.394/1996, incluindo os arts. 4º-A e 81-A.',
            meta: 'Presidência da República · texto compilado',
            href: 'https://www.planalto.gov.br/ccivil_03/leis/l9394.htm',
          },
          {
            id: 'resolucao-cne-ceb-2-2001',
            type: 'document',
            title: 'Resolução CNE/CEB nº 2/2001',
            description: 'Diretrizes Nacionais para a Educação Especial na Educação Básica.',
            meta: 'Ministério da Educação',
            href: 'https://www.gov.br/mec/pt-br/cne/normas-classificadas-por-assunto/normativos-sobre-educacao-especial',
          },
          {
            id: 'orientacoes-classe-hospitalar',
            type: 'document',
            title: 'Classe hospitalar e atendimento pedagógico domiciliar',
            description: 'Estratégias e orientações para a organização do atendimento.',
            meta: 'MEC/SEESP · 2002',
            href: 'https://dominiopublico.mec.gov.br/pesquisa/DetalheObraForm.do?co_obra=17039&select_action=',
          },
          {
            id: 'dcnei',
            type: 'document',
            title: 'Diretrizes Curriculares Nacionais para a Educação Infantil',
            description: 'Publicação que reúne a Resolução CNE/CEB nº 5/2009.',
            meta: 'Ministério da Educação',
            href: 'https://www.gov.br/mec/pt-br/acesso-a-informacao/media/seb/pdf/d_c_n_educacao_basica_nova.pdf',
          },
          {
            id: 'bncc',
            type: 'document',
            title: 'Base Nacional Comum Curricular',
            description: 'Referência curricular nacional para a Educação Infantil.',
            meta: 'Ministério da Educação',
            href: 'https://basenacionalcomum.mec.gov.br/',
          },
          {
            id: 'portaria-rn-533-2022',
            type: 'document',
            title: 'Portaria-SEI nº 533, de 6 de julho de 2022',
            description: 'Ato da SEEC/RN com orientações para implementação e funcionamento do Programa de Atendimento Educacional Hospitalar e Domiciliar do RN.',
            meta: 'Diário Oficial do Estado do Rio Grande do Norte',
            href: 'https://webdisk.diariooficial.rn.gov.br/Jornal/12022-07-22.pdf',
          },
          {
            id: 'portaria-rn-4522-2024',
            type: 'document',
            title: 'Portaria-SEI nº 4.522, de 26 de setembro de 2024',
            description: 'Ato da SEEC/RN sobre Educação Especial Inclusiva que contém seção específica sobre AEHD e atribuições de seus professores.',
            meta: 'Diário Oficial do Estado do Rio Grande do Norte',
            href: 'https://webdisk.diariooficial.rn.gov.br/Jornal/12024-09-27.pdf',
          },
        ],
      },
    ],
  },
]
