import type { ContentSection } from '../../types/content'
import { recursosComplementares } from './complementares'
import { literaturaNaturezaSections } from './literatura-natureza'

export const recursosSections: ContentSection[] = [
  {
    id: 'acervo-curadoria-nao-acumulacao',
    eyebrow: 'Situação pedagógica para reflexão',
    title: 'Um recurso, diferentes possibilidades de encontro',
    blocks: [
      {"type":"paragraph","text":"Imagine uma docente que leva uma caixa ao atendimento. O mesmo objeto pode abrir experiências diferentes conforme sua apresentação e o que a criança faz com ele."},
      { type: 'paragraph', text: 'A caixa pode ser apenas colocada diante da criança, sem que fique claro se ela pode tocá-la. Pode ser apresentada exclusivamente como recipiente, com a expectativa de que todos os usos sigam essa função. Também pode ser aproximada e disponibilizada de modo que a criança possa abri-la, produzir sons, colocar outros objetos, combiná-la com materiais ou transformá-la em uma construção.' },
      {"type":"paragraph","text":"Se a criança não usar a caixa, observe antes de concluir. O objeto pode estar pouco acessível, outro interesse pode ter surgido ou ela pode simplesmente não querer utilizá-lo."},
      { type: 'callout', tone: 'guidance', title: 'Para pensar', text: 'O que muda quando um mesmo recurso é apenas colocado, tem seu uso previamente determinado ou é disponibilizado com abertura para exploração e transformação? Que condições permitem à criança perceber que pode escolher, utilizar, modificar ou recusar o objeto?' },
    ],
  },
  {
    id: 'o-que-torna-recurso-pedagogico',
    eyebrow: 'Material, condições e experiência',
    title: 'O que torna um recurso pedagógico?',
    blocks: [
      {"type":"paragraph","text":"O Parecer CNE/CEB nº 20/2009 reconhece materiais, espaços, tempos e interações na organização das experiências. O valor pedagógico do recurso depende dessas relações e do que a criança pode fazer, comunicar e transformar."},
      {"type":"paragraph","text":"Aproximar, apoiar ou reposicionar um material pode abrir seu uso. Apresente possibilidades sem determinar uma única ação e sem exigir que todos os recursos sejam utilizados."},
    ],
  },
  {
    id: 'o-que-a-pesquisa-revelou-recursos',
    eyebrow: 'Resultados da pesquisa',
    title: 'O que a pesquisa revelou',
    blocks: [
      { type: 'paragraph', text: 'As narrativas analisadas na pesquisa que deu origem a este Caderno Digital mostram que as professoras participantes recorreram à adaptação e à produção de recursos para responder às necessidades encontradas nos atendimentos.' },
      { type: 'paragraph', text: 'Adaptar ou produzir um recurso, nessa perspectiva, não se reduz a confeccionar um objeto. Esses movimentos envolvem observar as condições concretas do encontro, considerar as possibilidades de participação da criança, selecionar materiais, rever formas de apresentação e decidir o que pode ser mantido, modificado ou substituído.' },
      { type: 'paragraph', text: 'As respostas construídas pelas professoras foram situadas. Por isso, não devem ser transformadas em modelos universais ou em uma lista de recursos indicados para todas as crianças. O que se mostra pertinente em um atendimento pode precisar de reorganização em outro, mesmo quando o material é semelhante.' },
      { type: 'paragraph', text: 'Observar o que mudou após adaptar um material ajuda a fundamentar a próxima escolha.' },
      { type: 'callout', tone: 'note', title: 'Uma leitura dos resultados', text: 'A pesquisa evidencia adaptação e produção de recursos nas práticas narradas pelas professoras. O princípio a preservar não é a repetição dos mesmos materiais, mas a atenção às condições concretas, à participação da criança e às decisões pedagógicas construídas em cada encontro.' },
    ],
  },
  {
    id: 'escolher-recurso-encontro',
    eyebrow: 'Seleção e curadoria',
    title: 'Escolher com qualidade, abertura e sentido',
    blocks: [
      {"type":"paragraph","text":"O manual Brinquedos e brincadeiras de creches destaca qualidade, diversidade, durabilidade, interesse, segurança e variedade de usos. Esses critérios alcançam materiais industrializados, artesanais, reutilizáveis ou produzidos por crianças e adultos, sem presumir a superioridade de uma categoria."},
      {"type":"paragraph","text":"O Parecer CNE/CEB nº 20/2009 relaciona a Educação Infantil à sensibilidade, à criatividade, à ludicidade e à diversidade cultural. Na curadoria, considere legibilidade, composição, qualidade visual e sonora e ausência de estereótipos."},
      {"type":"paragraph","text":"Cores e personagens conhecidos não garantem interesse; imagens e sons tampouco precisam ser simplificados em excesso."},
      {"type":"paragraph","text":"Na escolha, observe se o recurso admite combinação e transformação ou apenas uma resposta prevista."},
      {"type":"paragraph","text":"Oferta, conservação e renovação do acervo são também responsabilidades institucionais, reconhecidas pelo documento MEC/SEESP de 2002. A criatividade da docente não substitui essas condições. Compartilhamento, higienização e conservação seguem os protocolos locais."},
      {"type":"callout","tone":"guidance","title":"Antes de escolher um recurso","text":"O que a criança poderá fazer ou comunicar com o recurso? Há abertura para escolha e criação? Que repertórios culturais ele oferece? É acessível e adequado às condições do atendimento?"},
    ],
  },
  {
    id: 'organizar-escolher-participar',
    eyebrow: 'Visibilidade, acesso e disponibilidade',
    title: 'Organizar para perceber, escolher e participar',
    blocks: [
      {"type":"paragraph","text":"O manual do MEC/UNICEF relaciona a disposição e o alcance dos materiais à participação. Uma estante baixa pode apoiar escolhas em um espaço coletivo, mas o acesso de quem está no leito exige outra organização."},
      {"type":"paragraph","text":"O documento MEC/SEESP de 2002 reconhece a diversidade dos espaços de atendimento e a responsabilidade institucional pelos recursos. Suas recomendações tecnológicas refletem o período de publicação."},
      {"type":"paragraph","text":"Considere transporte, armazenamento e interrupções. Materiais móveis, uso individual ou compartilhado e guarda das produções dependem das condições e normas locais."},
      {"type":"paragraph","text":"Situação pedagógica para reflexão: a docente apresenta livros, peças, papéis, miniaturas e um objeto sonoro. A criança observa, mas não escolhe. A professora aproxima um conjunto menor e torna cada elemento mais visível."},
      {"type":"paragraph","text":"A criança pode escolher, pedir outro material ou continuar sem escolher. Não há regra de que menos seja sempre melhor: a mudança permite observar se a apresentação facilitou o acesso às possibilidades."},
    ],
  },
  {
    id: 'materiais-outros-sentidos',
    eyebrow: 'Acervo, combinação e transformação',
    title: 'Recursos estruturados, materiais abertos e produções das crianças',
    blocks: [
      {"type":"paragraph","text":"Um jogo tem regras e um quebra-cabeça propõe relações entre partes. Caixas, tecidos e blocos admitem funções mais variadas. Esses graus de abertura oferecem possibilidades distintas."},
      {"type":"paragraph","text":"Recursos estruturados podem favorecer investigação e estratégias compartilhadas. Materiais abertos podem ampliar combinações, mas não garantem autoria por si sós. O modo de uso depende da mediação e das escolhas infantis."},
      { type: 'paragraph', text: 'Materiais gráficos, jogos, miniaturas, objetos sonoros, elementos reutilizáveis e recursos produzidos na instituição podem conviver no acervo. Letras, números, escrita e relações matemáticas também podem estar presentes, desde que participem de situações significativas e não sejam reduzidos a treino mecânico, associação repetitiva ou verificação de respostas.' },
      { type: 'callout', tone: 'guidance', title: 'Quando o objeto não segue o uso imaginado', text: 'Situação pedagógica para reflexão: A docente aproxima blocos e pequenas figuras, imaginando uma construção. A criança desliza um bloco pela superfície e começa a produzir sons, combinando-os com o movimento de uma figura. A docente pode observar se esse uso é seguro e institucionalmente possível. Em vez de reconduzir imediatamente o bloco à construção, pode acolher a exploração, aproximar outro elemento ou deixar que siga sem acréscimos. O uso não previsto não representa necessariamente erro: pode revelar outra possibilidade e modificar o percurso.' },
    ],
  },
  {
    id: 'materialidades-culturais',
    eyebrow: 'Qualidade estética e cultural',
    title: 'Livros, imagens, sons e audiovisual como materialidades culturais',
    blocks: [
      { type: 'paragraph', text: 'Nos livros, formato, tamanho, peso, encadernação, papel, projeto gráfico e relação entre texto e imagem participam da experiência. Livros-imagem não são obras incompletas pela ausência de texto verbal: podem favorecer observação, interpretação e diferentes construções narrativas. Livros ilustrados, por sua vez, estabelecem relações variadas entre palavra, imagem, sequência e materialidade.' },
      {"type":"paragraph","text":"A publicação Literatura na Educação Infantil: acervos, espaços e mediações destaca a qualidade textual, temática e gráfica. Um acervo rico reúne gêneros, estilos visuais, autores, ilustradores e perspectivas diversos, oferecendo obras que mereçam ser reencontradas."},
      {"type":"paragraph","text":"Fotografias, ilustrações e reproduções artísticas precisam estar legíveis e bem posicionadas. Excesso de informação e estereótipos podem limitar a exploração."},
      {"type":"paragraph","text":"Na música, cuide da reprodução, do volume, da duração e da possibilidade de pausa. A criança pode cantar, mover-se ou apenas ouvir, sem uma execução esperada."},
      {"type":"paragraph","text":"No audiovisual, observe qualidade narrativa, visual e sonora, fonte, publicidade e reprodução automática. Assistir pode envolver antecipações e comentários quando há espaço para escolha e conversa."},
      {"type":"paragraph","text":"Situação pedagógica para reflexão: durante a leitura, o livro escorrega e fica distante da criança. A docente pode aproximá-lo, reposicioná-lo ou buscar outra sustentação."},
      {"type":"paragraph","text":"A criança pode indicar a melhor posição, ajudar a virar páginas ou apenas acompanhar. Observe se o ajuste favoreceu sua participação ou se é preciso tentar outra forma."},
    ],
  },
  {
    id: 'acessibilidade-reorganizar-recursos',
    eyebrow: 'Barreiras e possibilidades de participação',
    title: 'Acessibilidade: observar, reorganizar e olhar novamente',
    blocks: [
      {"type":"paragraph","text":"Observe a barreira concreta: suporte que se move, imagem distante, acionamento difícil ou uma forma de resposta que impede a criança de comunicar sua escolha. O diagnóstico, sozinho, não define a adaptação."},
      { type: 'paragraph', text: 'O Parecer CNE/CEB nº 20/2009 inclui a acessibilidade de espaços, materiais, objetos, brinquedos, instruções e formas de comunicação entre as condições das propostas de Educação Infantil. As Diretrizes do Desenho Universal para a Aprendizagem do CAST, versão 3.0, contribuem complementarmente ao propor diferentes meios de percepção, interação, ação, comunicação e expressão.' },
      {"type":"paragraph","text":"Depois de reorganizar, observe novamente. Aproximar um objeto pode facilitar o alcance e dificultar a visão do conjunto; reduzir peças pode tornar a escolha mais clara e limitar uma construção."},
      {"type":"paragraph","text":"Respeite os recursos de comunicação e tecnologia assistiva já utilizados pela criança e as orientações profissionais pertinentes. Prescrição de equipamentos e decisões clínicas não pertencem à atuação docente."},
      { type: 'paragraph', text: 'Uma barreira, diferentes possibilidades de reorganização:' },
      { type: 'list', items: [
        'Um suporte se desloca: enquanto a criança tenta desenhar, montar ou acionar um elemento, o suporte se move e interrompe sua ação. Pode ser possível estabilizá-lo, reposicioná-lo, mudar a superfície ou buscar outra sustentação. A docente observa se a reorganização ampliou a ação ou criou outra dificuldade.',
        'Um elemento visual não está facilmente acessível: uma imagem permanece distante ou pouco perceptível na posição em que a criança se encontra. Aproximá-la, reposicioná-la, alterar sua orientação ou ampliá-la quando possível são alternativas a considerar conforme o conteúdo, o espaço e a forma de participação.',
        'O acionamento dificulta a participação: um recurso depende de um toque, movimento ou comando que naquele momento dificulta seu uso. A docente pode reorganizar o modo de escolha, admitir outra resposta, mediar o acionamento sob orientação da criança ou optar por outro recurso. Apoiar não significa decidir ou realizar tudo em seu lugar.',
      ] },
    ],
  },
  {
    id: 'recursos-digitais-criacao-comunicacao',
    eyebrow: 'Tecnologia com propósito pedagógico',
    title: 'Recursos digitais, criação, comunicação e privacidade',
    blocks: [
      {"type":"paragraph","text":"Avalie que experiência o recurso digital torna possível naquele encontro."},
      { type: 'paragraph', text: 'O posicionamento da Early Childhood Australia sobre crianças e tecnologias digitais, publicado em 2025, propõe decisões deliberadas sobre quando, por que e como utilizar ou deixar de utilizar tecnologias. Embora não seja uma norma brasileira, a publicação oferece uma referência contemporânea para pensar interação, criação, comunicação, colaboração, qualidade dos conteúdos e participação infantil em contextos digitais.' },
      {"type":"paragraph","text":"Assistir a um curta ou ouvir uma música pode ser uma experiência cultural compartilhada. A autoria infantil depende das escolhas que a criança pode fazer, e não apenas do uso de um equipamento."},
      {"type":"paragraph","text":"Combine o digital com outros materiais quando isso ampliar a experiência. Uma narrativa sonora pode encontrar novos caminhos em um desenho ou uma construção."},
      { type: 'callout', tone: 'guidance', title: 'Um tablet, diferentes possibilidades', text: 'Em um encontro, o tablet pode servir à escolha de uma produção para assistir em conjunto; em outro, pode integrar uma narrativa sonora, a seleção de imagens, a comunicação de escolhas ou o registro autorizado de uma criação. Objetos e desenhos podem participar do mesmo percurso. A criança ainda pode preferir outro recurso, interromper seu uso ou recusá-lo.' },
      { type: 'callout', tone: 'note', title: 'Imagem, vídeo e privacidade', text: 'Os Parâmetros Nacionais de Qualidade e Equidade para a Educação Infantil incluem, entre seus critérios de qualidade, a autorização por escrito das famílias para a realização de registros de imagem de bebês e crianças, como fotografias e vídeos, e a consulta às próprias crianças antes do registro, com a finalidade de proteger seu direito à privacidade. O documento também prevê a participação ativa das crianças na construção da documentação pedagógica. Qualquer compartilhamento posterior precisa considerar sua finalidade e as orientações institucionais aplicáveis.' },
      {"type":"paragraph","text":"Observe ainda as normas hospitalares. A finalidade pedagógica não autoriza acessar, registrar ou interpretar prontuários, dados clínicos ou sistemas de saúde."},
    ],
  },
  {
    id: 'recursos-circulam-retornam-transformam',
    eyebrow: 'Continuidade, reflexão e aprofundamento',
    title: 'Recursos que circulam, retornam e se transformam',
    blocks: [
      { type: 'paragraph', text: 'Uma personagem desenhada pode retornar em outra narrativa. Uma construção pode receber novos elementos. Uma sequência de sons pode ser retomada. Um livro criado com a criança pode ser relido ou transformado. Uma fotografia, quando autorizada e realizada com consulta à criança, pode apoiar a memória compartilhada de uma criação.' },
      {"type":"paragraph","text":"Nem toda produção precisa ser guardada ou retomada. Ela pode circular, mudar ou ser deixada de lado conforme o interesse da criança. Torná-la documentação pedagógica exige outro trabalho de seleção e interpretação, discutido no módulo Planejamento."},
      {"type":"paragraph","text":"Reveja também o que você confeccionou: um painel pode ganhar legibilidade com menos elementos; um jogo pode oferecer poucas escolhas. Transformar ou retirar um recurso não desvaloriza o trabalho feito."},
      {"type":"paragraph","text":"A guarda e a circulação dependem das normas locais. Algumas produções poderão acompanhar a criança; outras não poderão permanecer ou circular entre espaços."},
      { type: 'paragraph', text: 'Para olhar novamente para os recursos:' },
      { type: 'list', items: [
        'O recurso amplia ou restringe as possibilidades de participação?',
        'A criança consegue perceber, escolher e utilizar o que está disponível?',
        'Há alguma barreira que pode ser reorganizada e o que mudou depois da reorganização?',
        'O material permite combinação ou transformação quando isso é pedagogicamente desejável?',
        'O que faz sentido manter, modificar, retirar ou deixar de oferecer?',
        'Há algum recurso ou produção que pode retornar em outro encontro sem criar obrigação de continuidade?',
      ] },
      { type: 'paragraph', text: 'Referências acadêmicas efetivamente utilizadas:' },
      { type: 'list', items: [
        'BRASIL. Conselho Nacional de Educação. Câmara de Educação Básica. Parecer CNE/CEB nº 20, de 11 de novembro de 2009: revisão das Diretrizes Curriculares Nacionais para a Educação Infantil. Brasília, DF: CNE, 2009.',
        'BRASIL. Ministério da Educação. Secretaria de Educação Básica. Brinquedos e brincadeiras de creches: manual de orientação pedagógica. Elaboração do texto final: Tizuko Morchida Kishimoto e Adriana Freyberger. Brasília, DF: MEC/SEB, 2012.',
        'BAPTISTA, Monica Correia; COELHO, Rita de Cássia Freitas; NEVES, Vanessa Ferraz Almeida; NUNES, Maria Fernanda Rezende; CORSINO, Patricia; BARRETO, Angela Rabelo (org.). Literatura na educação infantil: acervos, espaços e mediações. Brasília, DF: MEC, 2015.',
        'BRASIL. Ministério da Educação. Secretaria de Educação Básica. Parâmetros Nacionais de Qualidade e Equidade para a Educação Infantil. Brasília, DF: MEC, 2024.',
        'BRASIL. Ministério da Educação. Secretaria de Educação Especial. Classe hospitalar e atendimento pedagógico domiciliar: estratégias e orientações. Brasília, DF: MEC/SEESP, 2002.',
        'CAST. CAST Universal Design for Learning Guidelines version 3.0. Lynnfield, MA: CAST, 2024.',
        'EARLY CHILDHOOD AUSTRALIA. ECA Statement on young children and digital technologies. Revised version. Canberra: Early Childhood Australia, 2025.',
      ] },
      { type: 'resources', items: [
        { id: 'parecer-cne-ceb-20-2009', type: 'document', title: 'Parecer CNE/CEB nº 20/2009', description: 'Revisão das Diretrizes Curriculares Nacionais para a Educação Infantil.', meta: 'Conselho Nacional de Educação · 2009', href: 'https://www.gov.br/mec/pt-br/cne/parecer-ceb-2009' },
        { id: 'brinquedos-brincadeiras-creches', type: 'document', title: 'Brinquedos e brincadeiras de creches', description: 'Manual de orientação pedagógica sobre seleção, organização e uso de brinquedos e materiais.', meta: 'MEC/SEB · 2012', href: 'https://www.gov.br/mec/pt-br/acesso-a-informacao/institucional/estrutura-organizacional/orgaos-especificos-singulares/secretaria-de-educacao-basica/publicacoes/educacao-infantil' },
        { id: 'literatura-educacao-infantil', type: 'document', title: 'Literatura na Educação Infantil', description: 'Publicação sobre acervos, espaços, materialidade e qualidade textual, visual e gráfica.', meta: 'MEC · 2015', href: 'https://www.gov.br/mec/pt-br/media/seb/pdf/publicacoes/educacao_infantil/seminario_ebook_versao_impressao.pdf' },
        { id: 'parametros-qualidade-equidade', type: 'document', title: 'Parâmetros Nacionais de Qualidade e Equidade para a Educação Infantil', description: 'Referência para participação infantil, autorização de imagens e proteção da privacidade.', meta: 'MEC · 2024', href: 'https://www.gov.br/mec/pt-br/pnei/parametros-educacao-infantil.pdf' },
        { id: 'classe-hospitalar-mec-2002', type: 'document', title: 'Classe hospitalar e atendimento pedagógico domiciliar', description: 'Documento contextual sobre variabilidade dos espaços e dimensão institucional dos recursos.', meta: 'MEC/SEESP · 2002', href: 'https://dominiopublico.mec.gov.br/pesquisa/DetalheObraForm.do?co_obra=17039&select_action=' },
        { id: 'cast-udl-3', type: 'document', title: 'CAST UDL Guidelines 3.0', description: 'Referência complementar para analisar barreiras e diferentes formas de percepção, interação, ação e expressão.', meta: 'CAST · 2024', href: 'https://udlguidelines.cast.org/' },
        { id: 'eca-digital-technologies', type: 'document', title: 'Crianças, Adolescentes e Telas: Guia sobre Usos de Dispositivos Digitais', description: 'Documento oficial com orientações sobre o uso de telas e dispositivos digitais por crianças e adolescentes, incluindo recomendações relacionadas à primeira infância, à mediação de adultos e ao contexto educacional.', meta: 'Governo Federal · Secretaria de Comunicação Social da Presidência da República · 2025', href: 'https://www.gov.br/secom/pt-br/assuntos/uso-de-telas-por-criancas-e-adolescentes/guia' },
      ] },
    ],
  },
  ...recursosComplementares,
  ...literaturaNaturezaSections,
]
