import type { ContentSection } from '../../types/content'

export const legislacaoSections: ContentSection[] = [
  {
    id: 'direito-educacao-protecao-integral', eyebrow: 'Direito fundamental', title: 'Educação também é direito durante a hospitalização',
    blocks: [
      { type: 'paragraph', text: 'A Constituição Federal reconhece a educação como direito de todos e dever do Estado e da família. Também assegura prioridade absoluta à proteção de crianças e adolescentes. O Estatuto da Criança e do Adolescente articula o direito à educação à dignidade e à proteção integral.' },
      { type: 'paragraph', text: 'A internação ou o tratamento de saúde podem modificar as condições de presença e acesso às experiências educativas, mas não suspendem o direito à educação. Sua garantia durante a hospitalização requer organização e responsabilidade pública, consideradas as competências dos sistemas e das instituições envolvidos.' },
      { type: 'paragraph', text: 'Reconhecer esse direito não significa exigir participação a qualquer custo ou desconsiderar as condições concretas de cada encontro. Significa compreender que o atendimento educacional não é favor, distração ou ocupação do tempo: integra uma responsabilidade pública que precisa ser organizada pelos sistemas e pelas instituições competentes.' },
      { type: 'callout', tone: 'highlight', title: 'A criança permanece sujeito de direitos', text: 'Hospitalização, tratamento, pausa ou impossibilidade temporária de frequentar a instituição educacional não apagam o direito à educação, à brincadeira, à participação, à cultura, à escuta e ao respeito.' },
    ],
  },
  {
    id: 'legislacao-mapa-direitos-responsabilidades', eyebrow: 'Leitura normativa', title: 'Como ler os documentos deste módulo',
    blocks: [
      { type: 'paragraph', text: 'Este módulo não é um manual jurídico. Ele oferece referências para compreender direitos, responsabilidades, limites, formas de organização dos sistemas de ensino e implicações para a prática pedagógica. Diante de dúvidas sobre vigência, competência ou aplicação de uma norma, é necessário consultar a instância institucional responsável.' },
      { type: 'paragraph', text: 'Os documentos apresentados não possuem a mesma natureza nem o mesmo alcance. Em termos introdutórios, a Constituição ocupa posição superior na ordem jurídica brasileira e estabelece direitos e fundamentos; a lei pode estabelecer direitos, deveres e regras dentro da competência do ente que a edita; e o decreto pode regulamentar uma lei ou organizar sua execução pelo Poder Executivo, sem poder contrariá-la.' },
      { type: 'paragraph', text: 'Resoluções estabelecem diretrizes ou normas aprovadas por órgãos competentes, como os conselhos de educação. Pareceres apresentam análises e fundamentos técnicos e podem orientar ou fundamentar resoluções. Portarias são atos administrativos usados por uma autoridade para disciplinar matérias, procedimentos ou formas de organização no âmbito de sua competência. Documentos orientadores reúnem referências para a atuação, mas não equivalem automaticamente a uma lei ou a uma norma obrigatória.' },
      { type: 'paragraph', text: 'A Base Nacional Comum Curricular é um documento normativo curricular da Educação Básica. Ela orienta currículos e propostas pedagógicas, mas não deve ser confundida com lei, parecer ou resolução.' },
      { type: 'callout', tone: 'guidance', title: 'Antes de utilizar um documento', text: 'Observe sua fonte, autoria, data, vigência, esfera de aplicação, público, finalidade e alcance. Uma norma federal, uma portaria estadual e uma portaria municipal podem dialogar com o mesmo direito, mas não se aplicam indistintamente às mesmas redes e situações.' },
      { type: 'callout', tone: 'note', title: 'Atualização da consulta', text: 'Normas verificadas até agosto de 2026. A vigência e a aplicação administrativa devem ser confirmadas quando o documento for utilizado para orientar uma decisão concreta.' },
    ],
  },
  {
    id: 'crianca-sujeito-direitos', eyebrow: 'Proteção integral', title: 'A criança como sujeito de direitos',
    blocks: [
      { type: 'paragraph', text: 'Reconhecer a criança como sujeito de direitos tem implicações diretas para a prática pedagógica: significa considerá-la em sua integralidade, com história, vínculos, modos próprios de expressão e interesses. Também significa criar condições para que participe das experiências que lhe dizem respeito, de acordo com suas possibilidades e com o contexto.' },
      { type: 'paragraph', text: 'No trabalho pedagógico, essa compreensão se expressa na escuta, no respeito à iniciativa, na possibilidade de escolha e na atenção às manifestações de cansaço, pausa ou recusa. Esses princípios não substituem as normas da instituição nem as decisões da equipe de saúde; orientam a relação educativa dentro dos limites de atuação docente.' },
      { type: 'paragraph', text: 'Alguns documentos tratam de direitos relacionados à permanência no hospital sem regulamentar diretamente o atendimento educacional. A Resolução CONANDA nº 41/1995, de valor histórico e orientador, reúne direitos da criança e do adolescente hospitalizados. A Lei nº 11.104/2005 determina a instalação de brinquedotecas nas unidades de saúde que ofereçam atendimento pediátrico em regime de internação. A brinquedoteca pode ampliar oportunidades de brincar, mas não substitui o atendimento educacional organizado pela rede de ensino.' },
      { type: 'callout', tone: 'guidance', title: 'Direitos relacionados não são serviços equivalentes', text: 'Cuidado em saúde, recreação, brinquedoteca e atendimento educacional podem coexistir e dialogar. Cada um possui finalidade, responsabilidade profissional e forma de organização próprias.' },
    ],
  },
  {
    id: 'especificidade-educacao-infantil', eyebrow: 'Etapa com identidade própria', title: 'Educação Infantil: direito, currículo e continuidade da experiência educativa',
    blocks: [
      { type: 'paragraph', text: 'A oferta em contexto hospitalar não suspende a identidade pedagógica da Educação Infantil. O art. 31 da LDB estabelece que a avaliação nessa etapa ocorre mediante acompanhamento e registro do desenvolvimento das crianças, sem objetivo de promoção, mesmo para o acesso ao Ensino Fundamental. Aprovação, retenção e preparação antecipada para a etapa seguinte não devem organizar o trabalho com bebês e crianças pequenas.' },
      { type: 'paragraph', text: 'As Diretrizes Curriculares Nacionais para a Educação Infantil, instituídas pela Resolução CNE/CEB nº 5/2009 e fundamentadas pelo Parecer CNE/CEB nº 20/2009, reconhecem a criança como sujeito histórico e de direitos. Interações e brincadeira orientam as práticas, enquanto participação, expressão, vínculos e acesso ao patrimônio cultural integram a experiência educativa.' },
      { type: 'paragraph', text: 'A Resolução CNE/CEB nº 1/2024 estabelece Diretrizes Operacionais Nacionais de Qualidade e Equidade para a Educação Infantil e reforça responsabilidades dos sistemas e das instituições quanto a acesso, permanência, condições de oferta, qualidade e equidade. A BNCC, como documento normativo curricular, organiza direitos de aprendizagem e desenvolvimento e campos de experiências que podem apoiar o planejamento sem converter a Educação Infantil em uma sequência de conteúdos disciplinares.' },
      { type: 'paragraph', text: 'Em contexto hospitalar, continuidade não significa reproduzir mecanicamente a rotina da instituição de origem. Significa preservar o caráter educativo da etapa e criar condições para que interações, brincadeira, autoria e desenvolvimento integral continuem possíveis, respeitando a situação concreta da criança.' },
      { type: 'callout', tone: 'guidance', title: 'Situação pedagógica para reflexão: como ler a norma', text: 'Na Educação Infantil, a avaliação acompanha e registra o desenvolvimento das crianças, sem aprovação ou retenção como ocorre no Ensino Fundamental. Se uma norma usar esses termos, é necessário verificar se ela realmente se aplica à Educação Infantil. A interpretação deve ser compatível com o art. 31 da LDB e com as especificidades dessa etapa.' },
    ],
  },
  {
    id: 'aeh-aehd-classe-hospitalar-aee', eyebrow: 'Termos e alcances', title: 'Atendimento educacional hospitalar e domiciliar',
    blocks: [
      { type: 'paragraph', text: 'Atendimento Educacional Hospitalar (AEH) é uma denominação empregada para o atendimento educacional realizado em ambiente hospitalar. Atendimento Educacional Hospitalar e Domiciliar (AEHD) aparece em programas e normas que reúnem a oferta nos dois ambientes. O alcance concreto de cada expressão depende do documento e da rede em que é utilizada.' },
      { type: 'paragraph', text: 'Classe hospitalar é uma expressão presente em referências da Educação Especial e em documentos históricos do Ministério da Educação para nomear uma forma de organização do atendimento educacional em ambiente hospitalar. A Resolução CNE/CEB nº 2/2001 e o documento Classe hospitalar e atendimento pedagógico domiciliar, publicado pelo MEC/SEESP em 2002, são referências importantes dessa trajetória, mas o documento de 2002 não deve ser tomado como protocolo atual de segurança, higiene ou funcionamento hospitalar.' },
      { type: 'paragraph', text: 'Atendimento Educacional Especializado (AEE) pertence à modalidade da Educação Especial e tem função complementar ou suplementar à escolarização de seu público. Em publicação de 2026, o MEC utiliza a denominação “Atendimento Educacional Especializado em Ambiente Hospitalar e Domiciliar” para tratar da oferta do AEE nesse contexto ao público da Educação Especial. Essa denominação não se confunde com o atendimento educacional hospitalar destinado, de forma mais ampla, às crianças e aos estudantes hospitalizados.' },
      { type: 'paragraph', text: 'Não se pode concluir automaticamente que AEH, AEHD, classe hospitalar e AEE sejam equivalentes. Também não se pode concluir que a hospitalização, por si só, torne a criança público da Educação Especial. A modalidade, o público e a responsabilidade institucional precisam ser identificados a partir das normas e da organização da rede aplicáveis à situação.' },
      { type: 'callout', tone: 'note', title: 'A nomenclatura depende do contexto', text: 'Antes de empregar uma sigla, verifique em qual documento ela aparece, que público abrange, qual serviço designa e qual rede responde por sua oferta.' },
    ],
  },
  {
    id: 'educacao-internacao-tratamento-saude', eyebrow: 'Contribuições distintas', title: 'O que cada marco normativo contribui',
    blocks: [
      { type: 'paragraph', text: 'Constituição e ECA sustentam o direito à educação, a proteção integral e a prioridade atribuída às crianças e aos adolescentes. A LDB organiza a educação nacional, define incumbências dos sistemas e preserva as características das etapas da Educação Básica.' },
      { type: 'paragraph', text: 'O art. 4º-A da LDB, incluído pela Lei nº 13.716/2018, assegura atendimento educacional, durante o período de internação, ao aluno da Educação Básica internado para tratamento de saúde em regime hospitalar ou domiciliar por tempo prolongado, conforme regulamentação do Poder Público em sua esfera de competência. O dispositivo reconhece esse direito em uma situação específica e remete sua concretização à regulamentação competente.' },
      { type: 'paragraph', text: 'O art. 81-A, incluído pela Lei nº 14.952/2024, tem alcance diferente. Ele determina que os sistemas de ensino estabeleçam, para a Educação Básica e a Educação Superior, regime escolar especial para estudantes impossibilitados de frequentar as aulas em razão de tratamento ou de condição de saúde que impeça o acesso à instituição de ensino, além de contemplar mães estudantes lactantes. O acesso depende da comprovação da situação e da necessidade do regime especial para garantir continuidade e permanência nas atividades escolares, nos termos de regulamento.' },
      { type: 'paragraph', text: 'Assim, o art. 4º-A trata expressamente do atendimento educacional durante internação e tratamento prolongado em regime hospitalar ou domiciliar. O art. 81-A trata da instituição de regime escolar especial para as situações que enumera. Os dispositivos se relacionam, mas não são equivalentes; o art. 81-A não deve receber formulações que pertencem ao art. 4º-A nem uma exigência de articulação federativa que não esteja expressa em seu texto.' },
      { type: 'paragraph', text: 'As DCNEI, o Parecer CNE/CEB nº 20/2009, a Resolução CNE/CEB nº 1/2024 e a BNCC apoiam a compreensão curricular da Educação Infantil. Resoluções, pareceres e documentos orientadores ligados à Educação Especial ajudam a reconhecer trajetórias, conceitos e modalidades, observando sua vigência e seu alcance. Leis e portarias estaduais ou municipais, por sua vez, organizam o atendimento no âmbito das respectivas redes.' },
      { type: 'callout', tone: 'guidance', title: 'Ler a contribuição, não apenas o número', text: 'Um documento pode reconhecer um direito, organizar uma etapa, fundamentar uma diretriz, regulamentar uma rede ou conservar valor histórico e orientador. Identificar essa função evita aplicar todos os textos como se produzissem o mesmo efeito.' },
    ],
  },
  {
    id: 'direitos-crianca-hospitalizada-normas-adjacentes', eyebrow: 'Fronteiras institucionais', title: 'Direito educacional, organização pedagógica e atribuições da saúde',
    blocks: [
      { type: 'paragraph', text: 'O direito educacional reconhece a criança como titular do direito à educação e orienta o poder público a criar condições para sua garantia. A organização administrativa define, no âmbito de cada sistema e instituição, responsabilidades, autorizações, vínculos, registros e procedimentos para a oferta. Questões de interpretação normativa ou conflito de competências podem exigir decisão jurídica da instância responsável.' },
      { type: 'paragraph', text: 'A decisão pedagógica envolve observar, planejar, mediar, documentar e replanejar experiências coerentes com a etapa educacional e com as possibilidades do encontro. A docente pode ajustar tempos, linguagens, materiais e formas de participação, sem assumir sozinha decisões que pertencem à gestão, à rede ou a outras autoridades.' },
      { type: 'paragraph', text: 'O cuidado e a decisão clínica pertencem aos profissionais de saúde competentes. Condições de atendimento, restrições relacionadas ao tratamento, liberação para participação e medidas assistenciais não devem ser definidas ou interpretadas pela docente. A comunicação entre educação e saúde é necessária, mas não apaga os limites entre as áreas.' },
      { type: 'callout', tone: 'guidance', title: 'Responsabilidades que se articulam sem se confundir', text: 'À docente cabe a ação pedagógica. À rede e à gestão cabe organizar administrativamente a oferta. À instância jurídica competente cabe orientar dúvidas dessa natureza. À equipe de saúde cabem o cuidado e as decisões clínicas. O diálogo institucional aproxima essas responsabilidades sem transferi-las de uma área para outra.' },
    ],
  },
  {
    id: 'marco-normativo-rio-grande-norte', eyebrow: 'Contexto territorial', title: 'Marcos normativos locais: Rio Grande do Norte e Natal',
    blocks: [
      { type: 'paragraph', text: 'Os marcos nacionais sustentam direitos e diretrizes gerais. Estados e municípios, dentro de suas competências, podem editar normas e organizar o atendimento em suas redes. Por isso, é necessário identificar a esfera responsável antes de transportar um procedimento de uma rede para outra.' },
      { type: 'callout', tone: 'highlight', title: 'No Estado do Rio Grande do Norte', text: 'A Lei Estadual nº 10.320/2018 criou o Programa de Atendimento Educacional Hospitalar e Domiciliar no âmbito estadual. A lei delimita seu alcance à Rede Estadual de Ensino e prevê formas de oferta vinculadas à organização estadual e às cooperações nela indicadas.' },
      { type: 'paragraph', text: 'A Portaria-SEI nº 533, de 6 de julho de 2022, da SEEC/RN, estabelece orientações para implementação e funcionamento do Programa de AEHD. A Portaria-SEI nº 4.522, de 26 de setembro de 2024, também da SEEC/RN, institui diretrizes mais amplas para a Educação Especial Inclusiva na Rede Pública estadual e contém uma seção específica sobre o Atendimento Educacional Hospitalar e Domiciliar. O texto da Portaria nº 4.522 não a apresenta como alteração, complementação ou substituição formal da Portaria nº 533. A vigência e a aplicação administrativa desses atos devem ser confirmadas junto à SEEC/RN quando fundamentarem uma decisão concreta.' },
      { type: 'callout', tone: 'highlight', title: 'Atendimento Educacional Hospitalar e Domiciliar no Município de Natal', text: 'O Município de Natal possui marcos próprios relacionados à organização do atendimento educacional hospitalar e domiciliar. A Lei Municipal nº 6.365, de 21 de agosto de 2012, é referida como marco de implantação do Programa Classe Hospitalar no município. Mais recentemente, a Portaria nº 087/2026-GS/SME, de 28 de julho de 2026, estabelece orientações para esse atendimento e caracteriza o NAEHD/Natal como forma de atendimento a estudantes regularmente matriculados na Rede Municipal, vinculando-o à Secretaria Adjunta de Gestão Pedagógica da SME. Essa organização possui alcance municipal e não se confunde com o AEHD da Rede Estadual do Rio Grande do Norte.' },
      { type: 'paragraph', text: 'A lei e a portaria municipais ajudam a compreender como Natal organiza o atendimento no âmbito de sua competência. Elas não se aplicam automaticamente à Rede Estadual do Rio Grande do Norte, às redes de outros municípios ou a instituições fora do alcance definido em seus textos.' },
      { type: 'callout', tone: 'note', title: 'Âmbitos que não se confundem', text: 'Normas estaduais e municipais dialogam com os mesmos direitos educacionais, mas possuem esferas de aplicação distintas. Os atos da SEEC/RN orientam a Rede Estadual; os atos do Município de Natal e da SME/Natal alcançam a organização municipal nos limites de cada documento.' },
    ],
  },
  {
    id: 'normas-decisoes-pedagogicas', eyebrow: 'Leitura situada', title: 'Das normas às decisões pedagógicas',
    blocks: [
      { type: 'paragraph', text: 'Conhecer a legislação não produz uma resposta automática para cada encontro. As normas oferecem fundamentos, delimitam responsabilidades e indicam direitos que precisam ser considerados; a decisão pedagógica se constrói pela leitura desses marcos em diálogo com a etapa educacional, a proposta da rede e a observação da criança.' },
      { type: 'paragraph', text: 'Uma docente que reconhece o direito à continuidade educativa não precisa reproduzir uma rotina escolar indiferente ao contexto. Ela pode selecionar experiências coerentes com a Educação Infantil, acolher diferentes formas de participação, registrar o que observa e dialogar com a instituição de origem e com a organização responsável, conforme os procedimentos da rede.' },
      { type: 'paragraph', text: 'Também é importante reconhecer quando a questão ultrapassa sua atribuição. Dúvidas sobre matrícula, vínculo, frequência, autorização, responsabilidade entre redes ou validade de documentos precisam ser encaminhadas às instâncias administrativas ou jurídicas competentes. Questões clínicas devem permanecer com a equipe de saúde.' },
      { type: 'callout', tone: 'guidance', title: 'A norma orienta; a situação precisa ser compreendida', text: 'Relacionar legislação e prática não é transformar artigos em receitas. É usar os documentos para formular perguntas melhores, proteger direitos, reconhecer limites e sustentar decisões pedagógicas responsáveis.' },
    ],
  },
  {
    id: 'consultar-aplicar-marco-normativo', eyebrow: 'Consulta responsável', title: 'Para consultar, aprofundar e refletir',
    blocks: [
      { type: 'paragraph', text: 'Antes de utilizar um documento para fundamentar uma decisão, vale percorrer um roteiro breve de leitura:' },
      { type: 'list', items: ['Qual é a fonte oficial, quem produziu o documento e quando ele foi publicado?', 'O texto está vigente e existe norma posterior que o altere, complemente ou limite?', 'Em qual esfera e rede ele se aplica, e qual público está abrangido?', 'Qual é sua finalidade e o que efetivamente reconhece, regulamenta ou orienta?', 'O dispositivo alcança a situação concreta ou está sendo deslocado de outro contexto?', 'A questão exige decisão pedagógica ou confirmação da instância administrativa, jurídica, institucional ou de saúde competente?'] },
      { type: 'callout', tone: 'guidance', title: 'Confirme com a instância competente', text: 'Quando houver dúvida sobre vigência, alcance, conflito entre documentos, responsabilidade da rede ou procedimento institucional, consulte a gestão, o sistema de ensino ou a assessoria competente. O Caderno Digital apoia a leitura e a reflexão, mas não substitui orientação jurídica, administrativa ou institucional.' },
      { type: 'paragraph', text: 'Os documentos abaixo estão organizados por função e contexto para favorecer uma consulta situada, sem transformar o módulo em um catálogo de normas.' },
      { type: 'callout', tone: 'note', title: 'Direitos fundamentais', text: 'Textos que sustentam o direito à educação, a proteção integral e a prioridade de crianças e adolescentes.' },
      { type: 'resources', items: [
        { id: 'constituicao-federal', type: 'document', title: 'Constituição da República Federativa do Brasil de 1988', description: 'Direito à educação, proteção integral e prioridade absoluta.', href: 'https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm' },
        { id: 'eca', type: 'document', title: 'Lei nº 8.069/1990 — Estatuto da Criança e do Adolescente', description: 'Proteção integral, dignidade e direitos da criança e do adolescente.', href: 'https://www.planalto.gov.br/ccivil_03/leis/l8069compilado.htm' },
      ] },
      { type: 'callout', tone: 'note', title: 'LDB e atendimento', text: 'Lei geral da educação e alterações que tratam do atendimento educacional e do regime escolar especial.' },
      { type: 'resources', items: [
        { id: 'ldb-direito-educacao', type: 'document', title: 'Lei nº 9.394/1996 — Lei de Diretrizes e Bases da Educação Nacional', description: 'Organização da educação, responsabilidades dos sistemas e identidade das etapas.', href: 'https://www.planalto.gov.br/ccivil_03/leis/l9394compilado.htm' },
        { id: 'lei-13716-2018', type: 'document', title: 'Lei nº 13.716/2018', description: 'Inclui o art. 4º-A na LDB e assegura atendimento educacional na situação nele especificada.', href: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13716.htm' },
        { id: 'lei-14952-2024', type: 'document', title: 'Lei nº 14.952/2024', description: 'Inclui o art. 81-A na LDB e estabelece regime escolar especial para as situações que enumera.', href: 'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/l14952.htm' },
      ] },
      { type: 'callout', tone: 'note', title: 'Educação Infantil', text: 'Diretrizes, fundamentos e referências curriculares que preservam a identidade própria da etapa.' },
      { type: 'resources', items: [
        { id: 'dcnei', type: 'document', title: 'Resolução CNE/CEB nº 5/2009 — Diretrizes Curriculares Nacionais para a Educação Infantil', description: 'Diretrizes nacionais da Educação Infantil.', href: 'https://www.gov.br/mec/pt-br/acesso-a-informacao/media/seb/pdf/d_c_n_educacao_basica_nova.pdf' },
        { id: 'parecer-cne-ceb-20-2009', type: 'document', title: 'Parecer CNE/CEB nº 20/2009', description: 'Fundamentação das Diretrizes Curriculares Nacionais para a Educação Infantil.', href: 'https://www.gov.br/mec/pt-br/cne/parecer-ceb-2009' },
        { id: 'resolucao-cne-ceb-1-2024', type: 'document', title: 'Resolução CNE/CEB nº 1/2024', description: 'Diretrizes Operacionais Nacionais de Qualidade e Equidade para a Educação Infantil.', href: 'https://www.gov.br/mec/pt-br/cne/resolucoes-ceb-2024' },
        { id: 'bncc', type: 'document', title: 'Base Nacional Comum Curricular', description: 'Documento normativo curricular da Educação Básica; inclui direitos de aprendizagem e campos de experiências da Educação Infantil.', href: 'https://basenacionalcomum.mec.gov.br/' },
      ] },
      { type: 'callout', tone: 'note', title: 'Educação Especial e referências históricas', text: 'Documentos que ajudam a distinguir modalidades, nomenclaturas e a trajetória do atendimento.' },
      { type: 'resources', items: [
        { id: 'resolucao-cne-ceb-2-2001', type: 'document', title: 'Resolução CNE/CEB nº 2/2001', description: 'Referência histórica das Diretrizes Nacionais para a Educação Especial na Educação Básica.', href: 'https://portal.mec.gov.br/cne/arquivos/pdf/CEB0201.pdf' },
        { id: 'mec-classe-hospitalar-2002', type: 'document', title: 'Classe hospitalar e atendimento pedagógico domiciliar', description: 'Documento orientador e histórico do MEC/SEESP; não equivale a lei nem a protocolo hospitalar atual.', meta: 'MEC/SEESP · 2002', href: 'https://dominiopublico.mec.gov.br/pesquisa/DetalheObraForm.do?co_obra=17039&select_action=' },
        { id: 'decreto-12686-2025', type: 'document', title: 'Decreto nº 12.686/2025, alterado pelo Decreto nº 12.773/2025', description: 'Institui a Política Nacional de Educação Especial Inclusiva e a Rede Nacional de Educação Especial Inclusiva e contém disposições sobre organização e oferta do AEE.', href: 'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2025/decreto/d12686.htm' },
        { id: 'caderno-11-aeehd-2026', type: 'document', title: 'Atendimento Educacional Especializado em Ambiente Hospitalar e Domiciliar', description: 'Caderno pedagógico de 2026 sobre a oferta do AEE em ambiente hospitalar ou domiciliar ao público da Educação Especial.', meta: 'MEC · conteúdo produzido com participação de pesquisadores da UFC · 2026', href: 'https://www.gov.br/mec/pt-br/pneei/documentos' },
      ] },
      { type: 'callout', tone: 'note', title: 'Direitos relacionados', text: 'Referências que tratam de direitos durante a hospitalização e de espaços de brincar, sem substituir a regulamentação educacional.' },
      { type: 'resources', items: [
        { id: 'resolucao-conanda-41-1995', type: 'document', title: 'Resolução CONANDA nº 41/1995', description: 'Referência histórica sobre direitos da criança e do adolescente hospitalizados.', href: 'https://www.gov.br/participamaisbrasil/a-resolucao-n-41-de-09-13-de-outubro-de-1995' },
        { id: 'lei-11104-2005', type: 'document', title: 'Lei nº 11.104/2005', description: 'Dispõe sobre brinquedotecas em unidades de saúde com atendimento pediátrico em regime de internação.', href: 'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/l11104.htm' },
      ] },
      { type: 'callout', tone: 'note', title: 'Rio Grande do Norte', text: 'Marcos que organizam o atendimento no âmbito da Rede Estadual.' },
      { type: 'resources', items: [
        { id: 'lei-rn-10320-2018', type: 'document', title: 'Lei Estadual nº 10.320/2018', description: 'Cria o Programa de Atendimento Educacional Hospitalar e Domiciliar no âmbito do Rio Grande do Norte.', href: 'https://www.al.rn.leg.br/storage/legislacao/2021/o60c97okp3rloeeiu1al276y3o3ifu.pdf' },
        { id: 'portaria-rn-533-2022', type: 'document', title: 'Portaria-SEI nº 533, de 6 de julho de 2022', description: 'Ato da SEEC/RN que estabelece orientações para implementação e funcionamento do Programa de AEHD na Rede Estadual.', href: 'https://webdisk.diariooficial.rn.gov.br/Jornal/12022-07-22.pdf' },
        { id: 'portaria-rn-4522-2024', type: 'document', title: 'Portaria-SEI nº 4.522, de 26 de setembro de 2024', description: 'Institui diretrizes para a Educação Especial Inclusiva na Rede Pública estadual e contém disposições específicas sobre o Atendimento Educacional Hospitalar e Domiciliar.', href: 'https://webdisk.diariooficial.rn.gov.br/Jornal/12024-09-27.pdf' },
      ] },
      { type: 'callout', tone: 'note', title: 'Município de Natal', text: 'Marcos municipais vinculados à SME e à organização da Rede Municipal de Ensino.' },
      { type: 'resources', items: [
        { id: 'lei-natal-6365-2012', type: 'document', title: 'Lei Municipal nº 6.365/2012', description: 'Referida como marco de implantação do Programa Classe Hospitalar no Município de Natal. Link oficial permanente ainda não confirmado.' },
        { id: 'portaria-natal-087-2026', type: 'document', title: 'Portaria nº 087/2026-GS/SME', description: 'Estabelece orientações para o Atendimento Educacional em ambiente Hospitalar e Domiciliar no Município de Natal e dispõe sobre o NAEHD/Natal. Link oficial permanente ainda não confirmado.', meta: 'SME/Natal · 28 de julho de 2026' },
        { id: 'relatorio-gestao-sme-natal-2024', type: 'document', title: 'Relatório de Gestão 2024 — SME/Natal', description: 'Documento institucional que registra a oferta municipal e a formação de profissionais das classes hospitalares.', href: 'https://www.prefeitura.natal.br/storage/app/media/sme/RELATORIO_DE_GESTAO_2024.pdf' },
      ] },
    ],
  },
]
