import type { ContentSection } from '../../types/content'

export const educacaoInfantilSections: ContentSection[] = [
  {
    id: 'crianca-especificidade-educacao-infantil',
    eyebrow: 'Concepções fundamentais',
    title: 'A criança e a identidade da Educação Infantil',
    blocks: [
      { type: 'paragraph', text: 'As Diretrizes Curriculares Nacionais para a Educação Infantil (DCNEI) colocam a criança no centro do planejamento curricular e a reconhecem como sujeito histórico e de direitos. Nas interações, relações e práticas cotidianas, ela constrói sua identidade pessoal e coletiva, brinca, imagina, fantasia, deseja, aprende, observa, experimenta, narra, questiona, constrói sentidos sobre a natureza e a sociedade e produz cultura.' },
      { type: 'paragraph', text: 'Essa concepção orienta o olhar da docente para aquilo que a criança traz ao encontro: suas experiências, perguntas, ideias, lembranças, preferências e maneiras de se comunicar. A hospitalização faz parte do momento vivido, mas não define tudo o que ela é nem apaga sua participação na vida social e cultural.' },
      { type: 'paragraph', text: 'Este módulo se dirige especialmente ao trabalho com “Crianças pequenas (4 anos a 5 anos e 11 meses)”, conforme a nomenclatura da Base Nacional Comum Curricular (BNCC). Essa indicação permite localizar os objetivos de aprendizagem e desenvolvimento correspondentes à faixa etária, mas não estabelece um padrão único para todas as crianças. Cada uma chega ao atendimento com percursos, conhecimentos e formas de expressão próprios.' },
      { type: 'paragraph', text: 'A Educação Infantil também possui uma identidade curricular própria. Seu trabalho busca promover o desenvolvimento integral por meio de experiências, interações e brincadeiras. A continuidade com o Ensino Fundamental é importante, mas não significa antecipar conteúdos, cobranças ou formas de organização próprias da etapa seguinte.' },
      { type: 'callout', tone: 'highlight', title: 'A criança participa da construção da experiência', text: 'Colocar a criança no centro do planejamento não significa esperar que ela decida tudo. Significa reconhecer que suas perguntas, iniciativas, produções e maneiras de participar também influenciam o percurso construído com a docente.' },
    ],
  },
  {
    id: 'educar-cuidar-dimensoes-indissociaveis',
    eyebrow: 'Integralidade',
    title: 'Educar e cuidar nas escolhas cotidianas',
    blocks: [
      { type: 'paragraph', text: 'Na Educação Infantil, educar e cuidar são dimensões indissociáveis. Elas aparecem juntas na maneira como a docente organiza a experiência, apresenta os materiais, escuta a criança, acolhe seu tempo e cria condições para que ela participe.' },
      { type: 'paragraph', text: 'Essa relação não transforma a docente em profissional da saúde nem faz do cuidado uma tarefa separada do currículo. O cuidado pedagógico está presente, por exemplo, quando a proposta respeita o momento da criança, quando o espaço é organizado para favorecer sua participação ou quando uma ideia inicial é modificada porque o encontro tomou outro caminho.' },
      { type: 'paragraph', text: 'Ao mesmo tempo, educar não se limita a transmitir conteúdos. Envolve criar situações nas quais a criança possa brincar, conversar, imaginar, explorar materiais, fazer escolhas, experimentar diferentes linguagens e construir relações.' },
      { type: 'paragraph', text: 'A docente aprende sobre essas escolhas no próprio trabalho. Ao observar como cada criança participa, registrar o que aconteceu e retomar suas decisões, ela constrói conhecimentos que ajudam a planejar outros encontros e a reconhecer novas possibilidades de mediação.' },
      { type: 'callout', tone: 'guidance', title: 'Educar e cuidar fazem parte da mesma experiência', text: 'Essa relação não cria uma lista adicional de tarefas. Ela orienta a qualidade das escolhas curriculares e das relações construídas com a criança.' },
    ],
  },
  {
    id: 'interacoes-brincadeiras-eixos-estruturantes',
    eyebrow: 'Eixos estruturantes',
    title: 'Interações e brincadeira no centro das experiências',
    blocks: [
      { type: 'paragraph', text: 'As DCNEI definem as interações e a brincadeira como eixos norteadores das práticas pedagógicas da Educação Infantil. A BNCC retoma esses mesmos eixos como estruturantes das aprendizagens e do desenvolvimento.' },
      { type: 'paragraph', text: 'Isso importa porque brincar não é uma recompensa depois de uma tarefa nem apenas uma maneira de tornar um exercício mais atraente. Na brincadeira, a criança imagina situações, transforma objetos, experimenta papéis, cria regras, toma decisões, comunica ideias e interpreta aquilo que vive.' },
      { type: 'paragraph', text: 'A brincadeira pode surgir de diferentes maneiras. Pode começar com uma história, um objeto, um gesto, uma pergunta ou uma ideia da própria criança. Também pode mudar durante o encontro, fazer uma pausa, terminar antes do previsto ou não despertar seu interesse naquele momento.' },
      { type: 'paragraph', text: 'A interação, por sua vez, não depende necessariamente da presença de um grupo. Uma conversa entre a criança e a docente, a criação de uma história em conjunto, a escolha compartilhada de materiais ou a apresentação de um desenho a outra pessoa podem constituir interações significativas. Em um atendimento individual, há relação, troca e construção conjunta.' },
      { type: 'paragraph', text: 'No hospital, os espaços disponíveis, a duração do encontro e os materiais podem variar. Essas condições modificam a forma como a brincadeira acontece, mas não retiram sua importância. Uma experiência breve também pode acolher imaginação, escolha, curiosidade e criação.' },
      { type: 'callout', tone: 'highlight', title: 'Brincar pode mudar o percurso', text: 'Quando a criança transforma a proposta, inventa outro uso para o material ou prefere seguir uma ideia diferente, ela não está necessariamente se afastando da experiência. Pode estar construindo uma maneira própria de participar dela.' },
    ],
  },
  {
    id: 'direitos-aprendizagem-desenvolvimento',
    eyebrow: 'BNCC',
    title: 'Direitos de aprendizagem e desenvolvimento',
    blocks: [
      { type: 'paragraph', text: 'A BNCC apresenta seis direitos de aprendizagem e desenvolvimento para a Educação Infantil. Eles ajudam a docente a pensar as condições oferecidas às crianças e a ampliar seu olhar sobre as experiências.' },
      { type: 'list', items: [
        'Conviver: relacionar-se com crianças e adultos, conhecer diferentes modos de vida e aprender a respeitar as diferenças.',
        'Brincar: participar de diferentes brincadeiras, ampliando a imaginação, a criatividade e as experiências corporais, emocionais, sociais e culturais.',
        'Participar: envolver-se nas experiências, contribuir com ideias, fazer escolhas, formular perguntas, sugerir mudanças e tomar parte nas decisões que também dizem respeito à criança.',
        'Explorar: investigar movimentos, gestos, sons, formas, texturas, palavras, histórias, objetos, espaços, relações e transformações.',
        'Expressar: comunicar necessidades, emoções, dúvidas, descobertas, opiniões e interpretações por diferentes linguagens.',
        'Conhecer-se: construir identidades pessoais, sociais e culturais e uma imagem positiva de si nas experiências de cuidado, interação, brincadeira e participação.',
      ] },
      { type: 'paragraph', text: 'Esses direitos não são etapas sucessivas nem itens que precisem ser conferidos um a um. Uma experiência não precisa contemplar os seis ao mesmo tempo, e a docente não precisa provar que todos apareceram em cada encontro.' },
      { type: 'paragraph', text: 'Os direitos ajudam a formular perguntas sobre as condições de participação oferecidas à criança. Podem revelar, por exemplo, que uma proposta inicialmente centrada na produção de um objeto ganhou mais sentido na conversa, na investigação do material ou na história criada durante o encontro.' },
      { type: 'paragraph', text: 'Essa leitura exige atenção ao que efetivamente aconteceu. O currículo não se define apenas pela intenção inicial da docente, mas também pelos caminhos construídos na relação com a criança.' },
      { type: 'callout', tone: 'note', title: 'Direitos orientam o olhar', text: 'Os direitos de aprendizagem e desenvolvimento ajudam a docente a perceber possibilidades presentes na experiência. Eles não servem para enquadrar cada encontro em uma lista de resultados esperados.' },
    ],
  },
  {
    id: 'campos-experiencias-organizacao-curricular',
    eyebrow: 'Organização curricular',
    title: 'Campos de experiências: uma leitura integrada do currículo',
    blocks: [
      { type: 'paragraph', text: 'A BNCC organiza o currículo da Educação Infantil em cinco campos de experiências. Eles acolhem situações da vida cotidiana e os saberes das crianças, relacionando-os aos conhecimentos que fazem parte do patrimônio cultural.' },
      { type: 'list', items: [
        'O eu, o outro e o nós: envolve experiências de identidade, pertencimento, autonomia, convivência, cuidado de si e do outro, respeito e contato com diferentes modos de viver.',
        'Corpo, gestos e movimentos: reúne experiências nas quais o corpo participa da exploração, da expressão, da brincadeira, da comunicação e da criação.',
        'Traços, sons, cores e formas: envolve experiências estéticas e expressivas com desenho, pintura, modelagem, música, sons, imagens, materiais e manifestações artísticas e culturais.',
        'Escuta, fala, pensamento e imaginação: abrange experiências com conversas, perguntas, narrativas, literatura, faz de conta e cultura escrita, nas quais as crianças comunicam ideias e constroem sentidos.',
        'Espaços, tempos, quantidades, relações e transformações: envolve experiências de observação, comparação, investigação e formulação de hipóteses sobre ambientes, objetos, fenômenos, medidas, sequências, quantidades e mudanças.',
      ] },
      { type: 'paragraph', text: 'Os campos não são disciplinas nem cinco gavetas nas quais cada ação precisa ser colocada. Uma experiência pode atravessar diferentes campos, porque corpo, linguagem, relações, imaginação, investigação e criação aparecem frequentemente juntos.' },
      { type: 'paragraph', text: 'A docente também não precisa classificar cada gesto, fala ou produção da criança. Os campos ajudam a perceber dimensões da experiência que podem ser ampliadas, retomadas ou relacionadas a outras situações.' },
      { type: 'paragraph', text: 'Para “Crianças pequenas (4 anos a 5 anos e 11 meses)”, a BNCC apresenta objetivos de aprendizagem e desenvolvimento dentro de cada campo. A ordem dos códigos não representa uma sequência obrigatória nem uma hierarquia entre os objetivos.' },
      { type: 'paragraph', text: 'Esses objetivos não devem ser usados isoladamente como uma lista de comportamentos a conferir em cada criança. Sua leitura precisa considerar os campos de experiências, os direitos, as interações, as brincadeiras e a singularidade dos percursos infantis.' },
      { type: 'paragraph', text: 'Consultar os objetivos pode ajudar a docente a refletir sobre sua intencionalidade. A interpretação, porém, depende do conhecimento profissional e da observação do encontro: o que a criança já conhece, que perguntas surgiram, como participou e que outras possibilidades a experiência revelou.' },
      { type: 'callout', tone: 'guidance', title: 'Os campos se encontram no que a criança vive', text: 'Uma conversa pode envolver memória, imaginação, relação com o outro, gestos, desenho e investigação. O papel dos campos é ajudar a compreender essa experiência em sua riqueza, e não dividi-la artificialmente.' },
    ],
  },
  {
    id: 'linguagens-escuta-producao-sentidos',
    eyebrow: 'Expressão e participação',
    title: 'Diferentes linguagens e escuta da criança',
    blocks: [
      { type: 'paragraph', text: 'As crianças participam, criam e produzem sentidos por diferentes linguagens. Oralidade, literatura, cultura escrita, desenho, pintura, música, corpo, movimento, gesto, dramatização e faz de conta são algumas das maneiras pelas quais elas se relacionam com outras pessoas e com o mundo.' },
      { type: 'paragraph', text: 'Essas linguagens não precisam resultar em produtos iguais nem funcionar como técnicas a serem treinadas. Um desenho pode registrar uma ideia, iniciar uma conversa ou transformar-se em cenário para uma brincadeira. Um gesto pode comunicar uma escolha. Uma história pode ser ouvida, interrompida, modificada, dramatizada ou continuada de outra forma.' },
      { type: 'paragraph', text: 'A oralidade se desenvolve em situações reais de interlocução: conversar, narrar acontecimentos, inventar histórias, explicar uma brincadeira, fazer perguntas e escutar outras pessoas. A docente pode oferecer referências e participar da conversa sem controlar previamente tudo o que será dito.' },
      { type: 'paragraph', text: 'A literatura aproxima a criança de diferentes narrativas, palavras, imagens e formas de imaginar. O contato com livros, nomes, bilhetes, legendas e outras marcas escritas também favorece sua participação na cultura escrita.' },
      { type: 'paragraph', text: 'Essa aproximação não se confunde com antecipar a alfabetização formal. Copiar letras, repetir palavras ou escrever convencionalmente não deve se tornar condição para participar da experiência. A criança pode perguntar sobre a escrita, reconhecer nomes, produzir marcas gráficas, experimentar escritas espontâneas e descobrir seus usos sociais sem ser submetida a cobranças próprias do Ensino Fundamental.' },
      { type: 'paragraph', text: 'Escutar a criança envolve considerar sua fala e também seus gestos, silêncios, produções, perguntas, brincadeiras e escolhas. Oliveira (2022), ao trabalhar com narrativas de crianças, mães e docentes, mostra a importância de escutar as crianças como participantes da produção de conhecimentos sobre suas experiências educacionais.' },
      { type: 'paragraph', text: 'A participação pode acontecer de diferentes maneiras: a criança pode envolver-se diretamente, observar, sugerir mudanças, modificar o percurso ou fazer uma pausa. Também é preciso respeitar quando ela não deseja continuar a experiência. Essas manifestações ajudam a docente a compreender o encontro sem atribuir automaticamente causas clínicas ou emocionais.' },
      { type: 'callout', tone: 'highlight', title: 'A escuta pode transformar a proposta', text: 'Quando a docente considera o que a criança fala, mostra, cria ou escolhe, o planejamento deixa de ser apenas algo preparado para ela e passa a ser construído também a partir de sua participação.' },
    ],
  },
  {
    id: 'educacao-infantil-contexto-hospitalar',
    eyebrow: 'Implicações curriculares',
    title: 'Sustentar a Educação Infantil em outras condições de tempo e espaço',
    blocks: [
      { type: 'paragraph', text: 'Viver a Educação Infantil no contexto hospitalar significa sustentar sua identidade curricular em condições diferentes das encontradas em creches e pré-escolas. Os espaços disponíveis podem variar, o encontro pode ter duração incerta e uma experiência pode precisar mudar durante sua realização.' },
      { type: 'paragraph', text: 'Essas condições não criam outra Educação Infantil nem justificam uma versão reduzida da etapa. Relações, brincadeiras, diferentes linguagens, participação, investigação e criação continuam fazendo parte do currículo, ainda que apareçam em outros tempos, espaços e formas de organização.' },
      { type: 'paragraph', text: 'A continuidade educativa não depende de reproduzir rigidamente horários, folhas de atividade ou sequências da instituição de origem. Também não significa preencher cada encontro com tarefas para demonstrar que houve trabalho pedagógico. Ela se expressa na possibilidade de a criança continuar vivendo experiências com sentido, relacionadas ao que conhece, pergunta, imagina e deseja descobrir.' },
      { type: 'paragraph', text: 'Direitos, campos de experiências e objetivos da BNCC ajudam a docente a pensar essas possibilidades, mas não decidem sozinhos o que fazer. A leitura curricular envolve observar as condições do encontro, interpretar as manifestações da criança, fazer escolhas e rever o planejamento quando necessário.' },
      { type: 'paragraph', text: 'Na Educação Infantil, observar e registrar fazem parte do acompanhamento das experiências e do desenvolvimento das crianças. Os diferentes registros ajudam a docente a compreender os percursos vividos, refletir sobre o trabalho realizado e reorganizar tempos, espaços, materiais e propostas. Esse acompanhamento não tem objetivo de seleção, promoção ou classificação.' },
      { type: 'paragraph', text: 'Registrar não significa anotar tudo nem produzir um relatório após cada ação. Uma fala, uma pergunta, uma escolha, uma mudança na brincadeira ou uma solução criada pela criança pode ajudar a docente a perceber algo importante sobre a experiência. Ao retomar esses registros, ela também observa sua própria atuação: o que favoreceu a participação, o que não funcionou como esperado e o que pode ser transformado em outro encontro.' },
      { type: 'paragraph', text: 'É nesse movimento de observar, interpretar, registrar e retomar decisões que a docente amplia seus conhecimentos sobre o currículo e sobre sua prática. Os documentos oferecem fundamentos, mas a experiência cotidiana também produz saberes profissionais.' },
      { type: 'callout', tone: 'note', title: 'O currículo também se revela depois do encontro', text: 'Ao retomar o que aconteceu, a docente pode perceber sentidos e possibilidades que não estavam previstos no planejamento. O registro ajuda a preservar essas descobertas e a orientar novas escolhas.' },
    ],
  },
  {
    id: 'educacao-infantil-sem-antecipacoes',
    eyebrow: 'Síntese e referências',
    title: 'Currículo vivido, observado e retomado',
    blocks: [
      { type: 'paragraph', text: 'Na Educação Infantil, o currículo acontece nas experiências vividas pelas crianças. Direitos, campos e objetivos ajudam a orientar o olhar da docente, mas não funcionam como checklist nem substituem a escuta, a observação e o conhecimento profissional.' },
      { type: 'paragraph', text: 'No contexto hospitalar, as condições do encontro podem mudar. Isso não transforma a Educação Infantil em uma sequência de tarefas breves ou em preparação antecipada para o Ensino Fundamental. Brincar, interagir, escolher, explorar, criar e se expressar continuam sendo partes fundamentais do percurso.' },
      { type: 'paragraph', text: 'Observar e registrar ajudam a compreender como a criança participou e quais sentidos foram construídos. Também permitem que a docente reflita sobre suas decisões, reconheça os saberes produzidos na prática e encontre outros caminhos para o planejamento.' },
      { type: 'paragraph', text: 'Perguntas para retomar a experiência:' },
      { type: 'list', items: [
        'O que parece ter mobilizado a curiosidade ou o interesse da criança?',
        'De que maneiras ela participou, inclusive quando observou, fez uma pausa ou modificou a proposta?',
        'Que perguntas, ideias, brincadeiras ou criações surgiram durante o encontro?',
        'Houve algum caminho inesperado que merece ser retomado?',
        'O que minhas escolhas favoreceram e o que poderia ser organizado de outra maneira?',
        'O que os registros ajudam a compreender sobre a experiência da criança e sobre minha própria atuação?',
      ] },
      { type: 'paragraph', text: 'Referência acadêmica utilizada:' },
      { type: 'list', items: [
        'OLIVEIRA, Senadaht Barbosa Baracho Rodrigues de. Acompanhamento educacional no hospital e na escola regular: o que dizem crianças, mães e professoras. 2022. 285 f. Tese (Doutorado em Educação) — Programa de Pós-Graduação em Educação, Centro de Educação, Universidade Federal do Rio Grande do Norte, Natal, 2022.',
      ] },
      { type: 'paragraph', text: 'Documentos curriculares oficiais:' },
      { type: 'resources', items: [
        {
          id: 'dcnei',
          type: 'document',
          title: 'Resolução CNE/CEB nº 5/2009 — Diretrizes Curriculares Nacionais para a Educação Infantil',
          description: 'Fixa as Diretrizes Curriculares Nacionais para a Educação Infantil.',
          meta: 'Conselho Nacional de Educação · Câmara de Educação Básica',
          href: 'https://www.gov.br/mec/pt-br/cne/pdf/normas-classificadas-por-assunto/diretrizes-para-a-educacao-basica/rceb005_09.pdf/view',
        },
        {
          id: 'parecer-cne-ceb-20-2009',
          type: 'document',
          title: 'Parecer CNE/CEB nº 20/2009',
          description: 'Revisão das Diretrizes Curriculares Nacionais para a Educação Infantil.',
          meta: 'Conselho Nacional de Educação · Câmara de Educação Básica',
          href: 'https://www.gov.br/mec/pt-br/cne/parecer-ceb-2009',
        },
        {
          id: 'bncc',
          type: 'document',
          title: 'Base Nacional Comum Curricular',
          description: 'Documento normativo com a organização da etapa da Educação Infantil.',
          meta: 'Ministério da Educação · versão final',
          href: 'https://basenacionalcomum.mec.gov.br/',
        },
      ] },
    ],
  },
]
