import type { ContentSection } from '../../types/content'

export const planejamentoSections: ContentSection[] = [
  {
    id: 'planejar-construir-possibilidades',
    eyebrow: 'Planejamento aberto',
    title: 'Planejar na Educação Infantil em contexto hospitalar',
    blocks: [
      { type: 'paragraph', text: 'Planejar é uma ação pedagógica intencional. A docente parte do que conhece sobre a criança, das experiências que pretende favorecer e das condições concretas em que o encontro poderá acontecer. Essa leitura orienta as possibilidades que prepara e as alternativas que imagina.' },
      { type: 'paragraph', text: 'No hospital, não é possível antecipar completamente a experiência. O tempo e o espaço disponíveis podem mudar, assim como as formas de participação da criança. Uma proposta talvez comece de outra maneira, dure menos, se prolongue ou encontre um caminho que não havia sido previsto.' },
      { type: 'paragraph', text: 'A intencionalidade permanece nessa abertura. Saber por que fez determinadas escolhas permite à docente revê-las diante das manifestações da criança e das condições reais do encontro.' },
      { type: 'paragraph', text: 'A flexibilidade integra o planejamento porque prepara a docente para decidir durante a experiência. Ela chega ao encontro com referências, mas permanece atenta ao que se torna possível, necessário ou significativo.' },
      { type: 'callout', tone: 'highlight', title: 'Planejar é construir possibilidades', text: 'O planejamento prepara condições e sustenta uma intenção pedagógica. Seu percurso se define no encontro com a criança e pode ser reorganizado à medida que a experiência acontece.' },
    ],
  },
  {
    id: 'intencionalidade-possibilidades-experiencia',
    eyebrow: 'Intenção e abertura',
    title: 'Intencionalidade pedagógica e possibilidades de experiência',
    blocks: [
      { type: 'paragraph', text: 'A intencionalidade pedagógica expressa o que a docente pretende favorecer em uma experiência. Essa intenção orienta a escolha dos materiais, a organização do espaço e as decisões tomadas no encontro, seja para ampliar a imaginação, a investigação, a expressão ou as relações da criança.' },
      { type: 'paragraph', text: 'Ter clareza dessa intenção não determina uma resposta correta, um produto obrigatório ou o mesmo resultado para todas as crianças. A docente sabe por que propõe a experiência, mas o que será dito, produzido ou descoberto permanece aberto.' },
      { type: 'paragraph', text: 'Uma proposta voltada à imaginação, por exemplo, pode dar origem a uma narrativa, a uma pergunta ou a um uso inesperado do material. A criança talvez relacione o que vive a experiências anteriores ou prefira acompanhar em silêncio. O sentido pedagógico está nos caminhos que se constroem, não no cumprimento de todas essas possibilidades.' },
      { type: 'paragraph', text: 'As DCNEI e o Parecer CNE/CEB nº 20/2009 orientam a elaboração e a avaliação de propostas pedagógicas e curriculares para a Educação Infantil. Os direitos de aprendizagem e desenvolvimento, os campos de experiências, as interações e a brincadeira, apresentados na BNCC e discutidos no módulo anterior, permanecem como referências para as escolhas da docente. Não constituem, porém, uma sequência de itens a cumprir: ajudam a pensar que possibilidades estão sendo oferecidas e que dimensões da experiência podem ser ampliadas.' },
      { type: 'paragraph', text: 'No decorrer do encontro, uma pergunta, uma brincadeira iniciada pela criança ou uma forma inesperada de participação pode deslocar a intenção inicial. Ao revê-la, a docente reconhece que o planejamento se realiza com uma criança concreta, cujas manifestações participam da construção da experiência.' },
      { type: 'callout', tone: 'note', title: 'Intenção não é resultado determinado', text: 'A intenção pedagógica dá direção às escolhas da docente sem antecipar as respostas da criança. Assim, a experiência permanece aberta a diferentes percursos e sentidos.' },
    ],
  },
  {
    id: 'observar-escutar-planejar',
    eyebrow: 'Escuta e decisão',
    title: 'Observar e escutar para planejar',
    blocks: [
      { type: 'paragraph', text: 'A observação e a escuta oferecem elementos para que o planejamento não se restrinja ao que a docente imaginou antes do encontro. Ao acompanhar como a criança se aproxima da proposta, utiliza os materiais, formula perguntas, brinca, escolhe, cria e se comunica, a docente reúne indícios para compreender o que está acontecendo e decidir como continuar.' },
      { type: 'paragraph', text: 'Escutar não se limita a ouvir palavras. Gestos, movimentos, desenhos, narrativas, brincadeiras, produções, silêncios, recusas, aproximações e afastamentos também podem comunicar interesses, escolhas e modos de participar. Essas manifestações não têm um significado único ou automático. Precisam ser consideradas no contexto da experiência e em relação ao que a criança efetivamente faz ou comunica.' },
      { type: 'paragraph', text: 'Uma recusa, por exemplo, não deve ser tratada apenas como algo a superar para que a atividade prevista seja realizada. Ela pode indicar que a criança não deseja participar naquele momento, que prefere outro modo de aproximação ou que a proposta precisa ser modificada. Do mesmo modo, observar em silêncio não significa necessariamente ausência de participação. A docente precisa acompanhar o conjunto das manifestações antes de decidir se continua, oferece outra possibilidade, faz uma pausa ou encerra o encontro.' },
      { type: 'paragraph', text: 'Aquilo que a docente observa e escuta pode ajudá-la a decidir o que propor, modificar, interromper ou retomar. Também pode mostrar que determinada proposta perdeu o sentido e deve ser abandonada. A escuta participa do planejamento quando produz consequências nas decisões docentes, e não apenas quando confirma uma escolha já realizada.' },
      { type: 'paragraph', text: 'Essa observação permanece no campo pedagógico. A docente pode descrever manifestações percebidas e considerar informações relevantes comunicadas pela criança, pela família ou pelos profissionais responsáveis. Não lhe cabe, entretanto, atribuir diagnósticos ou estabelecer causas clínicas para comportamentos observados. Quando alguma condição relacionada ao atendimento precisa ser conhecida, ela deve ser comunicada pelos canais institucionais adequados e considerada somente naquilo que for pertinente à participação e à experiência educativa.' },
      { type: 'callout', tone: 'guidance', title: 'Observar para decidir', text: 'Observar e escutar não servem apenas para conhecer melhor a criança. Essas ações ajudam a docente a decidir o que pode continuar, o que precisa mudar e o que já não faz sentido sustentar naquele encontro.' },
    ],
  },
  {
    id: 'tempos-espacos-materiais-participacao',
    eyebrow: 'Condições da experiência',
    title: 'Organizar tempos, espaços, materiais e participação',
    blocks: [
      { type: 'paragraph', text: 'Organizar tempos, espaços, materiais e formas de participação faz parte da intencionalidade pedagógica. Essas dimensões não são apenas condições externas à experiência: elas interferem no que a criança pode fazer, escolher, explorar, comunicar e construir durante o encontro.' },
      { type: 'paragraph', text: 'A docente pode imaginar uma duração possível, mas não precisa transformá-la em tempo obrigatório. Uma experiência pode durar poucos minutos e ainda assim mobilizar uma pergunta, uma criação ou uma troca significativa. Em outro momento, pode prolongar-se porque a criança deseja continuar investigando, narrando ou brincando. Também pode ser interrompida e, quando houver sentido, retomada posteriormente.' },
      { type: 'paragraph', text: 'O planejamento considera os espaços realmente disponíveis e autorizados. Diferentes espaços oferecem possibilidades distintas de aproximação, movimento, interação e organização dos materiais. A docente trabalha com essas condições sem tomar como referência um ambiente ideal que talvez não esteja disponível. Quando o local muda, pode ser necessário rever a proposta, sua duração ou as formas previstas de participação.' },
      { type: 'paragraph', text: 'A escolha dos materiais também se relaciona à intenção da experiência. Mais do que reunir muitos recursos, importa considerar o que eles podem favorecer, como poderão ser utilizados naquele contexto e que alternativas existem caso algum deles não possa ser usado. Um material pode ser substituído, reorganizado ou retirado sem que a experiência perca necessariamente seu sentido pedagógico. Em outros casos, a impossibilidade de utilizá-lo pode levar a docente a construir outro percurso.' },
      { type: 'paragraph', text: 'Participar não significa executar uma tarefa da mesma forma ou produzir um resultado previamente estabelecido. A criança pode participar pela fala, pelo gesto, pela escolha, pela observação, pela manipulação de um material, pelo desenho, pela brincadeira, pela narrativa ou pelo silêncio. Pode também recusar uma proposta ou solicitar que ela seja interrompida.' },
      { type: 'paragraph', text: 'Essas formas não constituem uma lista fechada. Elas mostram que a participação pode assumir diferentes intensidades e percursos. Quando as escolhas da criança interferem efetivamente no tempo, nos materiais ou nos caminhos da experiência, sua participação deixa de ser apenas uma possibilidade anunciada e passa a integrar a construção do planejamento.' },
      { type: 'callout', tone: 'highlight', title: 'Participar também é interferir no percurso', text: 'Oferecer participação não consiste apenas em permitir que a criança escolha entre opções já definidas. Sua pergunta, sua iniciativa, seu silêncio ou sua recusa podem modificar o modo como a experiência continua.' },
    ],
  },
  {
    id: 'flexibilizar-interromper-adaptar-retomar',
    eyebrow: 'Flexibilidade em ação',
    title: 'Flexibilizar, interromper, adaptar e retomar',
    blocks: [
      { type: 'paragraph', text: 'O planejamento ganha forma no encontro. A duração, o espaço, os materiais, a linguagem e o percurso imaginado podem se modificar durante a experiência. Há propostas que pedem uma pausa ou uma retomada posterior; outras terminam antes do previsto ou nem chegam a acontecer.' },
      { type: 'paragraph', text: 'Essas mudanças podem mostrar que a docente percebeu as condições reais do encontro e respondeu ao que observou. Insistir apenas para cumprir o plano, ao contrário, esvazia a participação da criança e transforma a experiência em tarefa obrigatória.' },
      { type: 'paragraph', text: 'Interromper é uma decisão pedagógica quando a criança não deseja continuar, quando as condições comunicadas impedem a proposta naquele momento ou quando outro acontecimento mobiliza sua participação. Encerrar, nesses casos, preserva a responsabilidade docente: a continuidade não se justifica apenas porque algo foi previsto.' },
      { type: 'paragraph', text: 'Uma resposta flexível relaciona a decisão ao que acontece sem perder de vista a experiência que se pretendia favorecer. Às vezes, basta conservar o núcleo da intenção e mudar o tempo, o material ou a forma de participação. Em outras situações, será necessário rever a própria intenção.' },
      { type: 'paragraph', text: 'Nem todas as decisões cabem no que foi antecipado. Diante de um acontecimento inesperado, a docente recorre ao repertório, à sensibilidade e ao conhecimento profissional para compreender o que ainda faz sentido sustentar.' },
      { type: 'paragraph', text: 'Uma decisão tomada durante o encontro pode ser coerente com o planejamento. O que importa é relacioná-la às manifestações da criança e à intenção pedagógica, em vez de agir apenas para preencher o tempo. Flexibilidade envolve abertura e responsabilidade pelas escolhas realizadas.' },
      { type: 'paragraph', text: 'Na adaptação, mudam-se condições de acesso, formas de expressão, materiais, linguagem ou participação para preservar uma experiência com sentido. Isso não torna a proposta necessariamente mais simples, curta ou menos desafiadora, nem exige que a criança se ajuste a uma única maneira de realizá-la.' },
      { type: 'paragraph', text: 'Uma proposta interrompida não exige conclusão posterior. O registro ajuda a lembrar onde o percurso foi suspenso e o que mobilizava a criança. A retomada se justifica se ainda fizer sentido em outro encontro; caso contrário, será mais coerente construir uma nova possibilidade.' },
      { type: 'callout', tone: 'guidance', title: 'Adaptar sem esvaziar', text: 'Uma adaptação pedagógica preserva o sentido da experiência ao modificar alguma condição de acesso ou participação. Dependendo do encontro, essa escolha inclui interromper a proposta ou não realizá-la.' },
    ],
  },
  {
    id: 'registro-documentacao-pedagogica',
    eyebrow: 'Memória e interpretação',
    title: 'Registro e documentação pedagógica',
    blocks: [
      { type: 'paragraph', text: 'O registro docente ajuda a preservar acontecimentos que podem contribuir para a compreensão da experiência. Ele constitui uma seleção situada: a docente não registra tudo, mas escolhe falas, perguntas, gestos, produções, mudanças de percurso e decisões que considera relevantes para retomar e interpretar o que foi vivido.' },
      { type: 'paragraph', text: 'Registrar é construir uma memória profissional do encontro. Uma anotação pode recuperar o contexto em que a proposta aconteceu, as formas de participação observadas, as escolhas feitas pela criança, as modificações realizadas e as questões que permaneceram abertas. Ao voltar a esse material, a docente pode perceber relações que não estavam evidentes no momento da experiência e encontrar elementos para decisões posteriores.' },
      { type: 'paragraph', text: 'O registro precisa ser contextualizado. Em vez de afirmações gerais sobre como a criança “é”, interessa descrever o que aconteceu, o que ela fez ou comunicou e em quais condições. Expressões classificatórias, comparações entre crianças, diagnósticos e explicações clínicas não pertencem ao registro pedagógico docente.' },
      { type: 'paragraph', text: 'Os registros institucionais possuem finalidades próprias e seguem as normas e os fluxos do serviço. Podem documentar, por exemplo, a realização do atendimento e outras informações requeridas pela instituição ou pelo sistema de ensino. Embora possam se relacionar, o preenchimento de um registro administrativo não substitui o registro pedagógico voltado à compreensão da experiência.' },
      { type: 'paragraph', text: 'Neste Caderno, em diálogo com Marques e Almeida (2011, p. 417–421), a documentação pedagógica é compreendida como um processo de seleção, organização e reelaboração de registros que permite construir memória, interpretar e comunicar experiências. Esse processo vai além de acumular materiais e envolve definir o que se pretende documentar, com que finalidade e para quais interlocutores.' },
      { type: 'paragraph', text: 'Não é possível nem produtivo documentar tudo. Fotografias, desenhos, produções, relatos, falas registradas, portfólios e outras imagens podem integrar o processo, mas não constituem automaticamente documentação pedagógica. Seu sentido se constrói pela seleção, pela organização, pela contextualização, pela interpretação e pela finalidade atribuída aos registros.' },
      { type: 'paragraph', text: 'A documentação também pode favorecer o diálogo com a criança. Quando possível e pertinente, ela pode participar da escolha do que será preservado, retomar uma produção, comentar um registro, produzir seus próprios registros ou atribuir novos sentidos ao que viveu. Essa participação ajuda a construir a documentação com a criança, reconhecendo sua voz e suas diferentes formas de expressão.' },
      { type: 'paragraph', text: 'Os Parâmetros Nacionais de Qualidade e Equidade para a Educação Infantil incluem, entre seus critérios de qualidade, a autorização por escrito das famílias para a realização de registros de imagem de bebês e crianças, como fotografias e vídeos, e a consulta às próprias crianças antes do registro, com a finalidade de proteger seu direito à privacidade. O documento também prevê a participação ativa das crianças na construção da documentação dos processos pedagógicos. No contexto hospitalar, também precisam ser observadas as normas institucionais aplicáveis, a finalidade do uso e as condições autorizadas de compartilhamento.' },
      { type: 'callout', tone: 'note', title: 'Escrever sem rotular', text: 'Um registro pedagógico descreve acontecimentos e condições para apoiar a compreensão. Ele não define a criança por uma manifestação isolada nem transforma observações docentes em julgamentos ou explicações clínicas.' },
    ],
  },
  {
    id: 'acompanhar-replanejar',
    eyebrow: 'Avaliação na Educação Infantil',
    title: 'Acompanhar para replanejar',
    blocks: [
      { type: 'paragraph', text: 'Na Educação Infantil, avaliar significa acompanhar processos e experiências, e não medir desempenhos para classificar as crianças. O art. 31 da Lei de Diretrizes e Bases da Educação Nacional estabelece que a avaliação nessa etapa ocorre mediante acompanhamento e registro do desenvolvimento das crianças, sem objetivo de promoção, mesmo para o acesso ao Ensino Fundamental.' },
      { type: 'paragraph', text: 'As Diretrizes Curriculares Nacionais para a Educação Infantil orientam que as instituições criem procedimentos para acompanhar o trabalho pedagógico e avaliar o desenvolvimento das crianças sem objetivo de seleção, promoção ou classificação. Entre esses procedimentos estão a observação crítica e criativa das atividades, das brincadeiras e das interações e a utilização de múltiplos registros realizados por adultos e crianças.' },
      { type: 'paragraph', text: 'No trabalho pedagógico, acompanhar envolve voltar ao que foi observado e registrado para construir uma interpretação. Interpretar não significa procurar uma explicação definitiva para o comportamento da criança nem produzir um diagnóstico. Significa examinar pedagogicamente os acontecimentos, relacionando as manifestações da criança, as condições oferecidas e as decisões tomadas pela docente.' },
      { type: 'callout', tone: 'highlight', title: 'Da observação a novas decisões', text: 'Observação → registro → interpretação → novas decisões pedagógicas. A observação reúne indícios; o registro preserva alguns deles e seu contexto; a interpretação procura relações e sentidos possíveis; e, com base nela, a docente decide o que manter, modificar, interromper, retomar ou transformar.' },
      { type: 'paragraph', text: 'Ao interpretar uma experiência, a docente pode perguntar o que mobilizou a participação da criança, que interesses apareceram, que escolhas foram feitas e que caminhos surgiram de maneira inesperada. Também pode examinar o que favoreceu ou dificultou o encontro, que condições foram oferecidas e como suas próprias decisões interferiram no percurso.' },
      { type: 'paragraph', text: 'Assim, o acompanhamento não volta seu olhar apenas para a criança. Ele alcança a organização do tempo e do espaço, a escolha dos materiais, as possibilidades reais de participação, as intervenções da docente e os limites da proposta. Essa perspectiva evita que toda dificuldade seja atribuída à criança e permite analisar o próprio trabalho pedagógico.' },
      { type: 'paragraph', text: 'Replanejar não significa repetir automaticamente uma experiência até que ela seja concluída. Pode signific oferecer continuidade a um interesse, construir outra possibilidade, modificar uma escolha ou reconhecer que determinada proposta já não precisa ser retomada. Acompanhar permite compreender melhor o percurso vivido; essa compreensão sustenta novas decisões.' },
      { type: 'callout', tone: 'guidance', title: 'Acompanhar para compreender e replanejar', text: 'A avaliação acompanha processos, interroga as condições oferecidas e ajuda a docente a rever suas escolhas. Seu propósito não é produzir uma medida da criança, mas sustentar decisões pedagógicas mais coerentes com as experiências vividas.' },
    ],
  },
  {
    id: 'planejamento-movimento-continuo',
    eyebrow: 'Síntese e referências',
    title: 'Planejamento como movimento contínuo',
    blocks: [
      { type: 'paragraph', text: 'O planejamento não se encerra quando a experiência começa. Ele está presente antes do encontro, nas intenções e condições preparadas; durante o encontro, nas decisões tomadas diante do que acontece; e depois dele, quando a docente registra, interpreta e pensa em novas possibilidades.' },
      { type: 'callout', tone: 'highlight', title: 'Um movimento contínuo', text: 'Planejar → observar → realizar → registrar → interpretar → replanejar. Essas ações não formam uma sequência rígida: podem se sobrepor, mudar de ordem e ser retomadas mais de uma vez durante uma mesma experiência.' },
      { type: 'paragraph', text: 'Enquanto realiza uma proposta, a docente também observa, interpreta manifestações e modifica escolhas. Um registro breve pode ser feito durante a experiência ou retomado depois. O replanejamento pode começar ainda no encontro, quando um novo interesse ou percurso se torna perceptível.' },
      { type: 'paragraph', text: 'Em algumas situações, nem todas essas ações ocorrerão de maneira claramente separada. O valor desse movimento não está em cumprir etapas, mas em manter uma relação reflexiva entre as intenções da docente, as experiências vividas pela criança e as decisões que serão construídas a partir delas.' },
      { type: 'paragraph', text: 'Planejar, portanto, não consiste em elaborar uma proposta e verificar posteriormente se ela aconteceu como previsto. Consiste em preparar possibilidades, acompanhar o encontro, reconhecer o que se transforma durante o percurso e produzir conhecimentos que possam orientar outras escolhas.' },
      { type: 'paragraph', text: 'Ao longo do módulo, alguns princípios sustentaram essa compreensão:' },
      { type: 'list', items: [
        'A intencionalidade orienta a experiência sem determinar previamente seus resultados.',
        'A observação e a escuta interferem nas decisões de planejamento.',
        'Tempos, espaços, materiais e formas de participação compõem a ação pedagógica.',
        'Flexibilidade não é ausência de reflexão, e interromper uma proposta pode ser uma decisão coerente.',
        'O registro preserva elementos para a interpretação.',
        'O acompanhamento considera a criança, as condições oferecidas e as escolhas docentes.',
        'Replanejar é construir novas decisões a partir do que foi vivido.',
      ] },
      { type: 'paragraph', text: 'Como convite à reflexão, a docente pode se perguntar:' },
      { type: 'list', items: [
        'Que possibilidades pretendo favorecer e que abertura existe para outros percursos?',
        'O que as manifestações da criança estão produzindo em minhas decisões?',
        'As condições organizadas permitem diferentes formas de participação?',
        'O que merece ser preservado em registro e retomado com mais atenção?',
        'O que o encontro me ajuda a compreender sobre a experiência e sobre minhas escolhas?',
        'Que continuidade, modificação ou novo caminho faz sentido construir?',
      ] },
      { type: 'paragraph', text: 'Essas perguntas não constituem um roteiro obrigatório. Elas podem acompanhar diferentes momentos do trabalho e ajudar a manter o planejamento como um processo vivo, intencional e aberto à reflexão.' },
      { type: 'callout', tone: 'guidance', title: 'Planejar é permanecer em movimento', text: 'A docente prepara, observa, decide, registra e revê suas escolhas. O planejamento se constrói nesse movimento contínuo entre o que foi pensado, o que a experiência tornou possível e o que poderá ser reorganizado depois dela.' },
      { type: 'paragraph', text: 'Referências utilizadas:' },
      { type: 'resources', items: [
        { id: 'ldb-art-31', type: 'document', title: 'Lei nº 9.394/1996 — LDB, art. 31', description: 'Estabelece o acompanhamento e o registro, sem objetivo de promoção, na Educação Infantil.', meta: 'BRASIL. Presidência da República. Texto compilado.', href: 'https://www.planalto.gov.br/ccivil_03/leis/l9394compilado.htm' },
        { id: 'dcnei', type: 'document', title: 'Resolução CNE/CEB nº 5/2009 — DCNEI', description: 'Fixa as Diretrizes Curriculares Nacionais para a Educação Infantil.', meta: 'BRASIL. Conselho Nacional de Educação. Brasília, DF, 17 dez. 2009.', href: 'https://www.gov.br/mec/pt-br/cne/pdf/normas-classificadas-por-assunto/diretrizes-para-a-educacao-basica/rceb005_09.pdf/view' },
        { id: 'parecer-cne-ceb-20-2009', type: 'document', title: 'Parecer CNE/CEB nº 20/2009', description: 'Revisão das Diretrizes Curriculares Nacionais para a Educação Infantil.', meta: 'BRASIL. Conselho Nacional de Educação. Brasília, DF, 11 nov. 2009.', href: 'https://www.gov.br/mec/pt-br/cne/parecer-ceb-2009' },
        { id: 'bncc', type: 'document', title: 'Base Nacional Comum Curricular', description: 'Documento normativo com a organização da etapa da Educação Infantil.', meta: 'BRASIL. Ministério da Educação. Brasília, DF: MEC, 2018.', href: 'https://basenacionalcomum.mec.gov.br/' },
        { id: 'marques-almeida-documentacao-pedagogica', type: 'document', title: 'A documentação pedagógica na Educação Infantil', description: 'Artigo sobre registro, seleção, organização, memória, reflexão e documentação pedagógica.', meta: 'MARQUES, Amanda C. T. L.; ALMEIDA, Maria Isabel de. Revista de Educação Pública, v. 20, n. 44, p. 413–428, 2011. DOI: 10.29286/rep.v20i44.315.', href: 'https://periodicoscientificos.ufmt.br/ojs/index.php/educacaopublica/article/view/315' },
        { id: 'parametros-qualidade-equidade-ei-2024', type: 'document', title: 'Parâmetros Nacionais de Qualidade e Equidade para a Educação Infantil', description: 'Orienta registros, participação das crianças, autorização de imagens e proteção à privacidade.', meta: 'BRASIL. Ministério da Educação. Secretaria de Educação Básica. Brasília, DF: MEC, 2024.', href: 'https://www.gov.br/mec/pt-br/pnei/parametros-educacao-infantil.pdf' },
      ] },
    ],
  },
]
